import blue_default from "./colors/blue.mjs";
import cyan_default from "./colors/cyan.mjs";
import geekblue_default from "./colors/geekblue.mjs";
import gold_default from "./colors/gold.mjs";
import gray_default from "./colors/gray.mjs";
import green_default from "./colors/green.mjs";
import lime_default from "./colors/lime.mjs";
import magenta_default from "./colors/magenta.mjs";
import orange_default from "./colors/orange.mjs";
import primary_default from "./colors/primary.mjs";
import purple_default from "./colors/purple.mjs";
import red_default from "./colors/red.mjs";
import volcano_default from "./colors/volcano.mjs";
import yellow_default from "./colors/yellow.mjs";
import { colorScales } from "./colors/index.mjs";
import mauve_default from "./neutrals/mauve.mjs";
import olive_default from "./neutrals/olive.mjs";
import sage_default from "./neutrals/sage.mjs";
import sand_default from "./neutrals/sand.mjs";
import slate_default from "./neutrals/slate.mjs";
import { neutralColorScales } from "./neutrals/index.mjs";
import ColorScales_default from "./ColorScales/index.mjs";
import CssVar_default from "./CssVar/index.mjs";

export { ColorScales_default as ColorScales, CssVar_default as CssVar, blue_default as blue, colorScales, colorScales as colors, cyan_default as cyan, geekblue_default as geekblue, gold_default as gold, gray_default as gray, green_default as green, lime_default as lime, magenta_default as magenta, mauve_default as mauve, neutralColorScales, neutralColorScales as neutrals, olive_default as olive, orange_default as orange, primary_default as primary, purple_default as purple, red_default as red, sage_default as sage, sand_default as sand, slate_default as slate, volcano_default as volcano, yellow_default as yellow };