import Avatar from "./components/Avatar";
import BrandMono from "./components/BrandMono";
import Mono from "./components/Mono";
import { COLOR_PRIMARY, TITLE } from "./style";
var Icons = Mono;
Icons.Avatar = Avatar;
Icons.Text = BrandMono;
Icons.Brand = BrandMono;
Icons.colorPrimary = COLOR_PRIMARY;
Icons.title = TITLE;
export default Icons;