// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// Proxy is the model entity for the Proxy schema.
type Proxy struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Protocol holds the value of the "protocol" field.
	Protocol string `json:"protocol,omitempty"`
	// Host holds the value of the "host" field.
	Host string `json:"host,omitempty"`
	// Port holds the value of the "port" field.
	Port int `json:"port,omitempty"`
	// Username holds the value of the "username" field.
	Username *string `json:"username,omitempty"`
	// Password holds the value of the "password" field.
	Password *string `json:"password,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Region holds the value of the "region" field.
	Region *string `json:"region,omitempty"`
	// GroupName holds the value of the "group_name" field.
	GroupName *string `json:"group_name,omitempty"`
	// OvpnConfig holds the value of the "ovpn_config" field.
	OvpnConfig *string `json:"ovpn_config,omitempty"`
	// OvpnUsername holds the value of the "ovpn_username" field.
	OvpnUsername *string `json:"ovpn_username,omitempty"`
	// OvpnPassword holds the value of the "ovpn_password" field.
	OvpnPassword *string `json:"ovpn_password,omitempty"`
	// IsDedicated holds the value of the "is_dedicated" field.
	IsDedicated bool `json:"is_dedicated,omitempty"`
	// VpnStatus holds the value of the "vpn_status" field.
	VpnStatus *string `json:"vpn_status,omitempty"`
	// VpnExitIP holds the value of the "vpn_exit_ip" field.
	VpnExitIP *string `json:"vpn_exit_ip,omitempty"`
	// HealthStatus holds the value of the "health_status" field.
	HealthStatus *string `json:"health_status,omitempty"`
	// LatencyMs holds the value of the "latency_ms" field.
	LatencyMs *int `json:"latency_ms,omitempty"`
	// LastHealthAt holds the value of the "last_health_at" field.
	LastHealthAt *time.Time `json:"last_health_at,omitempty"`
	// HealthCheckFailures holds the value of the "health_check_failures" field.
	HealthCheckFailures int `json:"health_check_failures,omitempty"`
	// ProxyType holds the value of the "proxy_type" field.
	ProxyType string `json:"proxy_type,omitempty"`
	// Priority holds the value of the "priority" field.
	Priority int `json:"priority,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProxyQuery when eager-loading is set.
	Edges        ProxyEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProxyEdges holds the relations/edges for other nodes in the graph.
type ProxyEdges struct {
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e ProxyEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[0] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Proxy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case proxy.FieldIsDedicated:
			values[i] = new(sql.NullBool)
		case proxy.FieldID, proxy.FieldPort, proxy.FieldLatencyMs, proxy.FieldHealthCheckFailures, proxy.FieldPriority:
			values[i] = new(sql.NullInt64)
		case proxy.FieldName, proxy.FieldProtocol, proxy.FieldHost, proxy.FieldUsername, proxy.FieldPassword, proxy.FieldStatus, proxy.FieldRegion, proxy.FieldGroupName, proxy.FieldOvpnConfig, proxy.FieldOvpnUsername, proxy.FieldOvpnPassword, proxy.FieldVpnStatus, proxy.FieldVpnExitIP, proxy.FieldHealthStatus, proxy.FieldProxyType:
			values[i] = new(sql.NullString)
		case proxy.FieldCreatedAt, proxy.FieldUpdatedAt, proxy.FieldDeletedAt, proxy.FieldLastHealthAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Proxy fields.
func (_m *Proxy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case proxy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case proxy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case proxy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case proxy.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case proxy.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case proxy.FieldProtocol:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field protocol", values[i])
			} else if value.Valid {
				_m.Protocol = value.String
			}
		case proxy.FieldHost:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field host", values[i])
			} else if value.Valid {
				_m.Host = value.String
			}
		case proxy.FieldPort:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field port", values[i])
			} else if value.Valid {
				_m.Port = int(value.Int64)
			}
		case proxy.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = new(string)
				*_m.Username = value.String
			}
		case proxy.FieldPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field password", values[i])
			} else if value.Valid {
				_m.Password = new(string)
				*_m.Password = value.String
			}
		case proxy.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case proxy.FieldRegion:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field region", values[i])
			} else if value.Valid {
				_m.Region = new(string)
				*_m.Region = value.String
			}
		case proxy.FieldGroupName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field group_name", values[i])
			} else if value.Valid {
				_m.GroupName = new(string)
				*_m.GroupName = value.String
			}
		case proxy.FieldOvpnConfig:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ovpn_config", values[i])
			} else if value.Valid {
				_m.OvpnConfig = new(string)
				*_m.OvpnConfig = value.String
			}
		case proxy.FieldOvpnUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ovpn_username", values[i])
			} else if value.Valid {
				_m.OvpnUsername = new(string)
				*_m.OvpnUsername = value.String
			}
		case proxy.FieldOvpnPassword:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field ovpn_password", values[i])
			} else if value.Valid {
				_m.OvpnPassword = new(string)
				*_m.OvpnPassword = value.String
			}
		case proxy.FieldIsDedicated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_dedicated", values[i])
			} else if value.Valid {
				_m.IsDedicated = value.Bool
			}
		case proxy.FieldVpnStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vpn_status", values[i])
			} else if value.Valid {
				_m.VpnStatus = new(string)
				*_m.VpnStatus = value.String
			}
		case proxy.FieldVpnExitIP:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vpn_exit_ip", values[i])
			} else if value.Valid {
				_m.VpnExitIP = new(string)
				*_m.VpnExitIP = value.String
			}
		case proxy.FieldHealthStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field health_status", values[i])
			} else if value.Valid {
				_m.HealthStatus = new(string)
				*_m.HealthStatus = value.String
			}
		case proxy.FieldLatencyMs:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field latency_ms", values[i])
			} else if value.Valid {
				_m.LatencyMs = new(int)
				*_m.LatencyMs = int(value.Int64)
			}
		case proxy.FieldLastHealthAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_health_at", values[i])
			} else if value.Valid {
				_m.LastHealthAt = new(time.Time)
				*_m.LastHealthAt = value.Time
			}
		case proxy.FieldHealthCheckFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field health_check_failures", values[i])
			} else if value.Valid {
				_m.HealthCheckFailures = int(value.Int64)
			}
		case proxy.FieldProxyType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field proxy_type", values[i])
			} else if value.Valid {
				_m.ProxyType = value.String
			}
		case proxy.FieldPriority:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field priority", values[i])
			} else if value.Valid {
				_m.Priority = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Proxy.
// This includes values selected through modifiers, order, etc.
func (_m *Proxy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccounts queries the "accounts" edge of the Proxy entity.
func (_m *Proxy) QueryAccounts() *AccountQuery {
	return NewProxyClient(_m.config).QueryAccounts(_m)
}

// Update returns a builder for updating this Proxy.
// Note that you need to call Proxy.Unwrap() before calling this method if this Proxy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Proxy) Update() *ProxyUpdateOne {
	return NewProxyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Proxy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Proxy) Unwrap() *Proxy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Proxy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Proxy) String() string {
	var builder strings.Builder
	builder.WriteString("Proxy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("protocol=")
	builder.WriteString(_m.Protocol)
	builder.WriteString(", ")
	builder.WriteString("host=")
	builder.WriteString(_m.Host)
	builder.WriteString(", ")
	builder.WriteString("port=")
	builder.WriteString(fmt.Sprintf("%v", _m.Port))
	builder.WriteString(", ")
	if v := _m.Username; v != nil {
		builder.WriteString("username=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Password; v != nil {
		builder.WriteString("password=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.Region; v != nil {
		builder.WriteString("region=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.GroupName; v != nil {
		builder.WriteString("group_name=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OvpnConfig; v != nil {
		builder.WriteString("ovpn_config=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OvpnUsername; v != nil {
		builder.WriteString("ovpn_username=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.OvpnPassword; v != nil {
		builder.WriteString("ovpn_password=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_dedicated=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsDedicated))
	builder.WriteString(", ")
	if v := _m.VpnStatus; v != nil {
		builder.WriteString("vpn_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.VpnExitIP; v != nil {
		builder.WriteString("vpn_exit_ip=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.HealthStatus; v != nil {
		builder.WriteString("health_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LatencyMs; v != nil {
		builder.WriteString("latency_ms=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.LastHealthAt; v != nil {
		builder.WriteString("last_health_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("health_check_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.HealthCheckFailures))
	builder.WriteString(", ")
	builder.WriteString("proxy_type=")
	builder.WriteString(_m.ProxyType)
	builder.WriteString(", ")
	builder.WriteString("priority=")
	builder.WriteString(fmt.Sprintf("%v", _m.Priority))
	builder.WriteByte(')')
	return builder.String()
}

// Proxies is a parsable slice of Proxy.
type Proxies []*Proxy
