// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// ProxyUpdate is the builder for updating Proxy entities.
type ProxyUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyMutation
}

// Where appends a list predicates to the ProxyUpdate builder.
func (_u *ProxyUpdate) Where(ps ...predicate.Proxy) *ProxyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUpdate) SetUpdatedAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyUpdate) SetDeletedAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableDeletedAt(v *time.Time) *ProxyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyUpdate) ClearDeletedAt() *ProxyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ProxyUpdate) SetName(v string) *ProxyUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableName(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProxyUpdate) SetProtocol(v string) *ProxyUpdate {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableProtocol(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *ProxyUpdate) SetHost(v string) *ProxyUpdate {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableHost(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ProxyUpdate) SetPort(v int) *ProxyUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillablePort(v *int) *ProxyUpdate {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *ProxyUpdate) AddPort(v int) *ProxyUpdate {
	_u.mutation.AddPort(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *ProxyUpdate) SetUsername(v string) *ProxyUpdate {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableUsername(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *ProxyUpdate) ClearUsername() *ProxyUpdate {
	_u.mutation.ClearUsername()
	return _u
}

// SetPassword sets the "password" field.
func (_u *ProxyUpdate) SetPassword(v string) *ProxyUpdate {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillablePassword(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *ProxyUpdate) ClearPassword() *ProxyUpdate {
	_u.mutation.ClearPassword()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyUpdate) SetStatus(v string) *ProxyUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableStatus(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *ProxyUpdate) SetRegion(v string) *ProxyUpdate {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableRegion(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *ProxyUpdate) ClearRegion() *ProxyUpdate {
	_u.mutation.ClearRegion()
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *ProxyUpdate) SetGroupName(v string) *ProxyUpdate {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableGroupName(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// ClearGroupName clears the value of the "group_name" field.
func (_u *ProxyUpdate) ClearGroupName() *ProxyUpdate {
	_u.mutation.ClearGroupName()
	return _u
}

// SetOvpnConfig sets the "ovpn_config" field.
func (_u *ProxyUpdate) SetOvpnConfig(v string) *ProxyUpdate {
	_u.mutation.SetOvpnConfig(v)
	return _u
}

// SetNillableOvpnConfig sets the "ovpn_config" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableOvpnConfig(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetOvpnConfig(*v)
	}
	return _u
}

// ClearOvpnConfig clears the value of the "ovpn_config" field.
func (_u *ProxyUpdate) ClearOvpnConfig() *ProxyUpdate {
	_u.mutation.ClearOvpnConfig()
	return _u
}

// SetOvpnUsername sets the "ovpn_username" field.
func (_u *ProxyUpdate) SetOvpnUsername(v string) *ProxyUpdate {
	_u.mutation.SetOvpnUsername(v)
	return _u
}

// SetNillableOvpnUsername sets the "ovpn_username" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableOvpnUsername(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetOvpnUsername(*v)
	}
	return _u
}

// ClearOvpnUsername clears the value of the "ovpn_username" field.
func (_u *ProxyUpdate) ClearOvpnUsername() *ProxyUpdate {
	_u.mutation.ClearOvpnUsername()
	return _u
}

// SetOvpnPassword sets the "ovpn_password" field.
func (_u *ProxyUpdate) SetOvpnPassword(v string) *ProxyUpdate {
	_u.mutation.SetOvpnPassword(v)
	return _u
}

// SetNillableOvpnPassword sets the "ovpn_password" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableOvpnPassword(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetOvpnPassword(*v)
	}
	return _u
}

// ClearOvpnPassword clears the value of the "ovpn_password" field.
func (_u *ProxyUpdate) ClearOvpnPassword() *ProxyUpdate {
	_u.mutation.ClearOvpnPassword()
	return _u
}

// SetIsDedicated sets the "is_dedicated" field.
func (_u *ProxyUpdate) SetIsDedicated(v bool) *ProxyUpdate {
	_u.mutation.SetIsDedicated(v)
	return _u
}

// SetNillableIsDedicated sets the "is_dedicated" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableIsDedicated(v *bool) *ProxyUpdate {
	if v != nil {
		_u.SetIsDedicated(*v)
	}
	return _u
}

// SetVpnStatus sets the "vpn_status" field.
func (_u *ProxyUpdate) SetVpnStatus(v string) *ProxyUpdate {
	_u.mutation.SetVpnStatus(v)
	return _u
}

// SetNillableVpnStatus sets the "vpn_status" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableVpnStatus(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetVpnStatus(*v)
	}
	return _u
}

// ClearVpnStatus clears the value of the "vpn_status" field.
func (_u *ProxyUpdate) ClearVpnStatus() *ProxyUpdate {
	_u.mutation.ClearVpnStatus()
	return _u
}

// SetVpnExitIP sets the "vpn_exit_ip" field.
func (_u *ProxyUpdate) SetVpnExitIP(v string) *ProxyUpdate {
	_u.mutation.SetVpnExitIP(v)
	return _u
}

// SetNillableVpnExitIP sets the "vpn_exit_ip" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableVpnExitIP(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetVpnExitIP(*v)
	}
	return _u
}

// ClearVpnExitIP clears the value of the "vpn_exit_ip" field.
func (_u *ProxyUpdate) ClearVpnExitIP() *ProxyUpdate {
	_u.mutation.ClearVpnExitIP()
	return _u
}

// SetHealthStatus sets the "health_status" field.
func (_u *ProxyUpdate) SetHealthStatus(v string) *ProxyUpdate {
	_u.mutation.SetHealthStatus(v)
	return _u
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableHealthStatus(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetHealthStatus(*v)
	}
	return _u
}

// ClearHealthStatus clears the value of the "health_status" field.
func (_u *ProxyUpdate) ClearHealthStatus() *ProxyUpdate {
	_u.mutation.ClearHealthStatus()
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *ProxyUpdate) SetLatencyMs(v int) *ProxyUpdate {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableLatencyMs(v *int) *ProxyUpdate {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *ProxyUpdate) AddLatencyMs(v int) *ProxyUpdate {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (_u *ProxyUpdate) ClearLatencyMs() *ProxyUpdate {
	_u.mutation.ClearLatencyMs()
	return _u
}

// SetLastHealthAt sets the "last_health_at" field.
func (_u *ProxyUpdate) SetLastHealthAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetLastHealthAt(v)
	return _u
}

// SetNillableLastHealthAt sets the "last_health_at" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableLastHealthAt(v *time.Time) *ProxyUpdate {
	if v != nil {
		_u.SetLastHealthAt(*v)
	}
	return _u
}

// ClearLastHealthAt clears the value of the "last_health_at" field.
func (_u *ProxyUpdate) ClearLastHealthAt() *ProxyUpdate {
	_u.mutation.ClearLastHealthAt()
	return _u
}

// SetHealthCheckFailures sets the "health_check_failures" field.
func (_u *ProxyUpdate) SetHealthCheckFailures(v int) *ProxyUpdate {
	_u.mutation.ResetHealthCheckFailures()
	_u.mutation.SetHealthCheckFailures(v)
	return _u
}

// SetNillableHealthCheckFailures sets the "health_check_failures" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableHealthCheckFailures(v *int) *ProxyUpdate {
	if v != nil {
		_u.SetHealthCheckFailures(*v)
	}
	return _u
}

// AddHealthCheckFailures adds value to the "health_check_failures" field.
func (_u *ProxyUpdate) AddHealthCheckFailures(v int) *ProxyUpdate {
	_u.mutation.AddHealthCheckFailures(v)
	return _u
}

// SetProxyType sets the "proxy_type" field.
func (_u *ProxyUpdate) SetProxyType(v string) *ProxyUpdate {
	_u.mutation.SetProxyType(v)
	return _u
}

// SetNillableProxyType sets the "proxy_type" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableProxyType(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetProxyType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ProxyUpdate) SetPriority(v int) *ProxyUpdate {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillablePriority(v *int) *ProxyUpdate {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ProxyUpdate) AddPriority(v int) *ProxyUpdate {
	_u.mutation.AddPriority(v)
	return _u
}

// SetConfigVersion sets the "config_version" field.
func (_u *ProxyUpdate) SetConfigVersion(v int) *ProxyUpdate {
	_u.mutation.ResetConfigVersion()
	_u.mutation.SetConfigVersion(v)
	return _u
}

// SetNillableConfigVersion sets the "config_version" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableConfigVersion(v *int) *ProxyUpdate {
	if v != nil {
		_u.SetConfigVersion(*v)
	}
	return _u
}

// AddConfigVersion adds value to the "config_version" field.
func (_u *ProxyUpdate) AddConfigVersion(v int) *ProxyUpdate {
	_u.mutation.AddConfigVersion(v)
	return _u
}

// ClearConfigVersion clears the value of the "config_version" field.
func (_u *ProxyUpdate) ClearConfigVersion() *ProxyUpdate {
	_u.mutation.ClearConfigVersion()
	return _u
}

// SetLastConnectedAt sets the "last_connected_at" field.
func (_u *ProxyUpdate) SetLastConnectedAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetLastConnectedAt(v)
	return _u
}

// SetNillableLastConnectedAt sets the "last_connected_at" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableLastConnectedAt(v *time.Time) *ProxyUpdate {
	if v != nil {
		_u.SetLastConnectedAt(*v)
	}
	return _u
}

// ClearLastConnectedAt clears the value of the "last_connected_at" field.
func (_u *ProxyUpdate) ClearLastConnectedAt() *ProxyUpdate {
	_u.mutation.ClearLastConnectedAt()
	return _u
}

// SetConfigStale sets the "config_stale" field.
func (_u *ProxyUpdate) SetConfigStale(v bool) *ProxyUpdate {
	_u.mutation.SetConfigStale(v)
	return _u
}

// SetNillableConfigStale sets the "config_stale" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableConfigStale(v *bool) *ProxyUpdate {
	if v != nil {
		_u.SetConfigStale(*v)
	}
	return _u
}

// ClearConfigStale clears the value of the "config_stale" field.
func (_u *ProxyUpdate) ClearConfigStale() *ProxyUpdate {
	_u.mutation.ClearConfigStale()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *ProxyUpdate) AddAccountIDs(ids ...int64) *ProxyUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *ProxyUpdate) AddAccounts(v ...*Account) *ProxyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the ProxyMutation object of the builder.
func (_u *ProxyUpdate) Mutation() *ProxyMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *ProxyUpdate) ClearAccounts() *ProxyUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *ProxyUpdate) RemoveAccountIDs(ids ...int64) *ProxyUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *ProxyUpdate) RemoveAccounts(v ...*Account) *ProxyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ProxyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Proxy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := proxy.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "Proxy.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := proxy.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Proxy.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := proxy.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Proxy.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := proxy.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Proxy.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Proxy.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := proxy.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Proxy.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := proxy.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "Proxy.group_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OvpnUsername(); ok {
		if err := proxy.OvpnUsernameValidator(v); err != nil {
			return &ValidationError{Name: "ovpn_username", err: fmt.Errorf(`ent: validator failed for field "Proxy.ovpn_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OvpnPassword(); ok {
		if err := proxy.OvpnPasswordValidator(v); err != nil {
			return &ValidationError{Name: "ovpn_password", err: fmt.Errorf(`ent: validator failed for field "Proxy.ovpn_password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VpnStatus(); ok {
		if err := proxy.VpnStatusValidator(v); err != nil {
			return &ValidationError{Name: "vpn_status", err: fmt.Errorf(`ent: validator failed for field "Proxy.vpn_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VpnExitIP(); ok {
		if err := proxy.VpnExitIPValidator(v); err != nil {
			return &ValidationError{Name: "vpn_exit_ip", err: fmt.Errorf(`ent: validator failed for field "Proxy.vpn_exit_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthStatus(); ok {
		if err := proxy.HealthStatusValidator(v); err != nil {
			return &ValidationError{Name: "health_status", err: fmt.Errorf(`ent: validator failed for field "Proxy.health_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProxyType(); ok {
		if err := proxy.ProxyTypeValidator(v); err != nil {
			return &ValidationError{Name: "proxy_type", err: fmt.Errorf(`ent: validator failed for field "Proxy.proxy_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxy.Table, proxy.Columns, sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxy.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxy.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(proxy.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(proxy.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(proxy.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(proxy.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(proxy.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(proxy.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxy.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(proxy.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(proxy.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(proxy.FieldGroupName, field.TypeString, value)
	}
	if _u.mutation.GroupNameCleared() {
		_spec.ClearField(proxy.FieldGroupName, field.TypeString)
	}
	if value, ok := _u.mutation.OvpnConfig(); ok {
		_spec.SetField(proxy.FieldOvpnConfig, field.TypeString, value)
	}
	if _u.mutation.OvpnConfigCleared() {
		_spec.ClearField(proxy.FieldOvpnConfig, field.TypeString)
	}
	if value, ok := _u.mutation.OvpnUsername(); ok {
		_spec.SetField(proxy.FieldOvpnUsername, field.TypeString, value)
	}
	if _u.mutation.OvpnUsernameCleared() {
		_spec.ClearField(proxy.FieldOvpnUsername, field.TypeString)
	}
	if value, ok := _u.mutation.OvpnPassword(); ok {
		_spec.SetField(proxy.FieldOvpnPassword, field.TypeString, value)
	}
	if _u.mutation.OvpnPasswordCleared() {
		_spec.ClearField(proxy.FieldOvpnPassword, field.TypeString)
	}
	if value, ok := _u.mutation.IsDedicated(); ok {
		_spec.SetField(proxy.FieldIsDedicated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VpnStatus(); ok {
		_spec.SetField(proxy.FieldVpnStatus, field.TypeString, value)
	}
	if _u.mutation.VpnStatusCleared() {
		_spec.ClearField(proxy.FieldVpnStatus, field.TypeString)
	}
	if value, ok := _u.mutation.VpnExitIP(); ok {
		_spec.SetField(proxy.FieldVpnExitIP, field.TypeString, value)
	}
	if _u.mutation.VpnExitIPCleared() {
		_spec.ClearField(proxy.FieldVpnExitIP, field.TypeString)
	}
	if value, ok := _u.mutation.HealthStatus(); ok {
		_spec.SetField(proxy.FieldHealthStatus, field.TypeString, value)
	}
	if _u.mutation.HealthStatusCleared() {
		_spec.ClearField(proxy.FieldHealthStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(proxy.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(proxy.FieldLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.LatencyMsCleared() {
		_spec.ClearField(proxy.FieldLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.LastHealthAt(); ok {
		_spec.SetField(proxy.FieldLastHealthAt, field.TypeTime, value)
	}
	if _u.mutation.LastHealthAtCleared() {
		_spec.ClearField(proxy.FieldLastHealthAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HealthCheckFailures(); ok {
		_spec.SetField(proxy.FieldHealthCheckFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHealthCheckFailures(); ok {
		_spec.AddField(proxy.FieldHealthCheckFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProxyType(); ok {
		_spec.SetField(proxy.FieldProxyType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(proxy.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(proxy.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConfigVersion(); ok {
		_spec.SetField(proxy.FieldConfigVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfigVersion(); ok {
		_spec.AddField(proxy.FieldConfigVersion, field.TypeInt, value)
	}
	if _u.mutation.ConfigVersionCleared() {
		_spec.ClearField(proxy.FieldConfigVersion, field.TypeInt)
	}
	if value, ok := _u.mutation.LastConnectedAt(); ok {
		_spec.SetField(proxy.FieldLastConnectedAt, field.TypeTime, value)
	}
	if _u.mutation.LastConnectedAtCleared() {
		_spec.ClearField(proxy.FieldLastConnectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConfigStale(); ok {
		_spec.SetField(proxy.FieldConfigStale, field.TypeBool, value)
	}
	if _u.mutation.ConfigStaleCleared() {
		_spec.ClearField(proxy.FieldConfigStale, field.TypeBool)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ProxyUpdateOne is the builder for updating a single Proxy entity.
type ProxyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUpdateOne) SetUpdatedAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyUpdateOne) SetDeletedAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableDeletedAt(v *time.Time) *ProxyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
	}
	return _u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyUpdateOne) ClearDeletedAt() *ProxyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
}

// SetName sets the "name" field.
func (_u *ProxyUpdateOne) SetName(v string) *ProxyUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableName(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetProtocol sets the "protocol" field.
func (_u *ProxyUpdateOne) SetProtocol(v string) *ProxyUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
}

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableProtocol(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
	}
	return _u
}

// SetHost sets the "host" field.
func (_u *ProxyUpdateOne) SetHost(v string) *ProxyUpdateOne {
	_u.mutation.SetHost(v)
	return _u
}

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableHost(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetHost(*v)
	}
	return _u
}

// SetPort sets the "port" field.
func (_u *ProxyUpdateOne) SetPort(v int) *ProxyUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
}

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillablePort(v *int) *ProxyUpdateOne {
	if v != nil {
		_u.SetPort(*v)
	}
	return _u
}

// AddPort adds value to the "port" field.
func (_u *ProxyUpdateOne) AddPort(v int) *ProxyUpdateOne {
	_u.mutation.AddPort(v)
	return _u
}

// SetUsername sets the "username" field.
func (_u *ProxyUpdateOne) SetUsername(v string) *ProxyUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
}

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableUsername(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
	}
	return _u
}

// ClearUsername clears the value of the "username" field.
func (_u *ProxyUpdateOne) ClearUsername() *ProxyUpdateOne {
	_u.mutation.ClearUsername()
	return _u
}

// SetPassword sets the "password" field.
func (_u *ProxyUpdateOne) SetPassword(v string) *ProxyUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
}

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillablePassword(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
	}
	return _u
}

// ClearPassword clears the value of the "password" field.
func (_u *ProxyUpdateOne) ClearPassword() *ProxyUpdateOne {
	_u.mutation.ClearPassword()
	return _u
}

// SetStatus sets the "status" field.
func (_u *ProxyUpdateOne) SetStatus(v string) *ProxyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableStatus(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetRegion sets the "region" field.
func (_u *ProxyUpdateOne) SetRegion(v string) *ProxyUpdateOne {
	_u.mutation.SetRegion(v)
	return _u
}

// SetNillableRegion sets the "region" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableRegion(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetRegion(*v)
	}
	return _u
}

// ClearRegion clears the value of the "region" field.
func (_u *ProxyUpdateOne) ClearRegion() *ProxyUpdateOne {
	_u.mutation.ClearRegion()
	return _u
}

// SetGroupName sets the "group_name" field.
func (_u *ProxyUpdateOne) SetGroupName(v string) *ProxyUpdateOne {
	_u.mutation.SetGroupName(v)
	return _u
}

// SetNillableGroupName sets the "group_name" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableGroupName(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetGroupName(*v)
	}
	return _u
}

// ClearGroupName clears the value of the "group_name" field.
func (_u *ProxyUpdateOne) ClearGroupName() *ProxyUpdateOne {
	_u.mutation.ClearGroupName()
	return _u
}

// SetOvpnConfig sets the "ovpn_config" field.
func (_u *ProxyUpdateOne) SetOvpnConfig(v string) *ProxyUpdateOne {
	_u.mutation.SetOvpnConfig(v)
	return _u
}

// SetNillableOvpnConfig sets the "ovpn_config" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableOvpnConfig(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetOvpnConfig(*v)
	}
	return _u
}

// ClearOvpnConfig clears the value of the "ovpn_config" field.
func (_u *ProxyUpdateOne) ClearOvpnConfig() *ProxyUpdateOne {
	_u.mutation.ClearOvpnConfig()
	return _u
}

// SetOvpnUsername sets the "ovpn_username" field.
func (_u *ProxyUpdateOne) SetOvpnUsername(v string) *ProxyUpdateOne {
	_u.mutation.SetOvpnUsername(v)
	return _u
}

// SetNillableOvpnUsername sets the "ovpn_username" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableOvpnUsername(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetOvpnUsername(*v)
	}
	return _u
}

// ClearOvpnUsername clears the value of the "ovpn_username" field.
func (_u *ProxyUpdateOne) ClearOvpnUsername() *ProxyUpdateOne {
	_u.mutation.ClearOvpnUsername()
	return _u
}

// SetOvpnPassword sets the "ovpn_password" field.
func (_u *ProxyUpdateOne) SetOvpnPassword(v string) *ProxyUpdateOne {
	_u.mutation.SetOvpnPassword(v)
	return _u
}

// SetNillableOvpnPassword sets the "ovpn_password" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableOvpnPassword(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetOvpnPassword(*v)
	}
	return _u
}

// ClearOvpnPassword clears the value of the "ovpn_password" field.
func (_u *ProxyUpdateOne) ClearOvpnPassword() *ProxyUpdateOne {
	_u.mutation.ClearOvpnPassword()
	return _u
}

// SetIsDedicated sets the "is_dedicated" field.
func (_u *ProxyUpdateOne) SetIsDedicated(v bool) *ProxyUpdateOne {
	_u.mutation.SetIsDedicated(v)
	return _u
}

// SetNillableIsDedicated sets the "is_dedicated" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableIsDedicated(v *bool) *ProxyUpdateOne {
	if v != nil {
		_u.SetIsDedicated(*v)
	}
	return _u
}

// SetVpnStatus sets the "vpn_status" field.
func (_u *ProxyUpdateOne) SetVpnStatus(v string) *ProxyUpdateOne {
	_u.mutation.SetVpnStatus(v)
	return _u
}

// SetNillableVpnStatus sets the "vpn_status" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableVpnStatus(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetVpnStatus(*v)
	}
	return _u
}

// ClearVpnStatus clears the value of the "vpn_status" field.
func (_u *ProxyUpdateOne) ClearVpnStatus() *ProxyUpdateOne {
	_u.mutation.ClearVpnStatus()
	return _u
}

// SetVpnExitIP sets the "vpn_exit_ip" field.
func (_u *ProxyUpdateOne) SetVpnExitIP(v string) *ProxyUpdateOne {
	_u.mutation.SetVpnExitIP(v)
	return _u
}

// SetNillableVpnExitIP sets the "vpn_exit_ip" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableVpnExitIP(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetVpnExitIP(*v)
	}
	return _u
}

// ClearVpnExitIP clears the value of the "vpn_exit_ip" field.
func (_u *ProxyUpdateOne) ClearVpnExitIP() *ProxyUpdateOne {
	_u.mutation.ClearVpnExitIP()
	return _u
}

// SetHealthStatus sets the "health_status" field.
func (_u *ProxyUpdateOne) SetHealthStatus(v string) *ProxyUpdateOne {
	_u.mutation.SetHealthStatus(v)
	return _u
}

// SetNillableHealthStatus sets the "health_status" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableHealthStatus(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetHealthStatus(*v)
	}
	return _u
}

// ClearHealthStatus clears the value of the "health_status" field.
func (_u *ProxyUpdateOne) ClearHealthStatus() *ProxyUpdateOne {
	_u.mutation.ClearHealthStatus()
	return _u
}

// SetLatencyMs sets the "latency_ms" field.
func (_u *ProxyUpdateOne) SetLatencyMs(v int) *ProxyUpdateOne {
	_u.mutation.ResetLatencyMs()
	_u.mutation.SetLatencyMs(v)
	return _u
}

// SetNillableLatencyMs sets the "latency_ms" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableLatencyMs(v *int) *ProxyUpdateOne {
	if v != nil {
		_u.SetLatencyMs(*v)
	}
	return _u
}

// AddLatencyMs adds value to the "latency_ms" field.
func (_u *ProxyUpdateOne) AddLatencyMs(v int) *ProxyUpdateOne {
	_u.mutation.AddLatencyMs(v)
	return _u
}

// ClearLatencyMs clears the value of the "latency_ms" field.
func (_u *ProxyUpdateOne) ClearLatencyMs() *ProxyUpdateOne {
	_u.mutation.ClearLatencyMs()
	return _u
}

// SetLastHealthAt sets the "last_health_at" field.
func (_u *ProxyUpdateOne) SetLastHealthAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetLastHealthAt(v)
	return _u
}

// SetNillableLastHealthAt sets the "last_health_at" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableLastHealthAt(v *time.Time) *ProxyUpdateOne {
	if v != nil {
		_u.SetLastHealthAt(*v)
	}
	return _u
}

// ClearLastHealthAt clears the value of the "last_health_at" field.
func (_u *ProxyUpdateOne) ClearLastHealthAt() *ProxyUpdateOne {
	_u.mutation.ClearLastHealthAt()
	return _u
}

// SetHealthCheckFailures sets the "health_check_failures" field.
func (_u *ProxyUpdateOne) SetHealthCheckFailures(v int) *ProxyUpdateOne {
	_u.mutation.ResetHealthCheckFailures()
	_u.mutation.SetHealthCheckFailures(v)
	return _u
}

// SetNillableHealthCheckFailures sets the "health_check_failures" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableHealthCheckFailures(v *int) *ProxyUpdateOne {
	if v != nil {
		_u.SetHealthCheckFailures(*v)
	}
	return _u
}

// AddHealthCheckFailures adds value to the "health_check_failures" field.
func (_u *ProxyUpdateOne) AddHealthCheckFailures(v int) *ProxyUpdateOne {
	_u.mutation.AddHealthCheckFailures(v)
	return _u
}

// SetProxyType sets the "proxy_type" field.
func (_u *ProxyUpdateOne) SetProxyType(v string) *ProxyUpdateOne {
	_u.mutation.SetProxyType(v)
	return _u
}

// SetNillableProxyType sets the "proxy_type" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableProxyType(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetProxyType(*v)
	}
	return _u
}

// SetPriority sets the "priority" field.
func (_u *ProxyUpdateOne) SetPriority(v int) *ProxyUpdateOne {
	_u.mutation.ResetPriority()
	_u.mutation.SetPriority(v)
	return _u
}

// SetNillablePriority sets the "priority" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillablePriority(v *int) *ProxyUpdateOne {
	if v != nil {
		_u.SetPriority(*v)
	}
	return _u
}

// AddPriority adds value to the "priority" field.
func (_u *ProxyUpdateOne) AddPriority(v int) *ProxyUpdateOne {
	_u.mutation.AddPriority(v)
	return _u
}

// SetConfigVersion sets the "config_version" field.
func (_u *ProxyUpdateOne) SetConfigVersion(v int) *ProxyUpdateOne {
	_u.mutation.ResetConfigVersion()
	_u.mutation.SetConfigVersion(v)
	return _u
}

// SetNillableConfigVersion sets the "config_version" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableConfigVersion(v *int) *ProxyUpdateOne {
	if v != nil {
		_u.SetConfigVersion(*v)
	}
	return _u
}

// AddConfigVersion adds value to the "config_version" field.
func (_u *ProxyUpdateOne) AddConfigVersion(v int) *ProxyUpdateOne {
	_u.mutation.AddConfigVersion(v)
	return _u
}

// ClearConfigVersion clears the value of the "config_version" field.
func (_u *ProxyUpdateOne) ClearConfigVersion() *ProxyUpdateOne {
	_u.mutation.ClearConfigVersion()
	return _u
}

// SetLastConnectedAt sets the "last_connected_at" field.
func (_u *ProxyUpdateOne) SetLastConnectedAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetLastConnectedAt(v)
	return _u
}

// SetNillableLastConnectedAt sets the "last_connected_at" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableLastConnectedAt(v *time.Time) *ProxyUpdateOne {
	if v != nil {
		_u.SetLastConnectedAt(*v)
	}
	return _u
}

// ClearLastConnectedAt clears the value of the "last_connected_at" field.
func (_u *ProxyUpdateOne) ClearLastConnectedAt() *ProxyUpdateOne {
	_u.mutation.ClearLastConnectedAt()
	return _u
}

// SetConfigStale sets the "config_stale" field.
func (_u *ProxyUpdateOne) SetConfigStale(v bool) *ProxyUpdateOne {
	_u.mutation.SetConfigStale(v)
	return _u
}

// SetNillableConfigStale sets the "config_stale" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableConfigStale(v *bool) *ProxyUpdateOne {
	if v != nil {
		_u.SetConfigStale(*v)
	}
	return _u
}

// ClearConfigStale clears the value of the "config_stale" field.
func (_u *ProxyUpdateOne) ClearConfigStale() *ProxyUpdateOne {
	_u.mutation.ClearConfigStale()
	return _u
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *ProxyUpdateOne) AddAccountIDs(ids ...int64) *ProxyUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *ProxyUpdateOne) AddAccounts(v ...*Account) *ProxyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// Mutation returns the ProxyMutation object of the builder.
func (_u *ProxyUpdateOne) Mutation() *ProxyMutation {
	return _u.mutation
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *ProxyUpdateOne) ClearAccounts() *ProxyUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *ProxyUpdateOne) RemoveAccountIDs(ids ...int64) *ProxyUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *ProxyUpdateOne) RemoveAccounts(v ...*Account) *ProxyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// Where appends a list predicates to the ProxyUpdate builder.
func (_u *ProxyUpdateOne) Where(ps ...predicate.Proxy) *ProxyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyUpdateOne) Select(field string, fields ...string) *ProxyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Proxy entity.
func (_u *ProxyUpdateOne) Save(ctx context.Context) (*Proxy, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
	}
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUpdateOne) SaveX(ctx context.Context) *Proxy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ProxyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *ProxyUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
		}
		v := proxy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
	return nil
}

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Proxy.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Protocol(); ok {
		if err := proxy.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "Proxy.protocol": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Host(); ok {
		if err := proxy.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Proxy.host": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Username(); ok {
		if err := proxy.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Proxy.username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Password(); ok {
		if err := proxy.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Proxy.password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := proxy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Proxy.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Region(); ok {
		if err := proxy.RegionValidator(v); err != nil {
			return &ValidationError{Name: "region", err: fmt.Errorf(`ent: validator failed for field "Proxy.region": %w`, err)}
		}
	}
	if v, ok := _u.mutation.GroupName(); ok {
		if err := proxy.GroupNameValidator(v); err != nil {
			return &ValidationError{Name: "group_name", err: fmt.Errorf(`ent: validator failed for field "Proxy.group_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OvpnUsername(); ok {
		if err := proxy.OvpnUsernameValidator(v); err != nil {
			return &ValidationError{Name: "ovpn_username", err: fmt.Errorf(`ent: validator failed for field "Proxy.ovpn_username": %w`, err)}
		}
	}
	if v, ok := _u.mutation.OvpnPassword(); ok {
		if err := proxy.OvpnPasswordValidator(v); err != nil {
			return &ValidationError{Name: "ovpn_password", err: fmt.Errorf(`ent: validator failed for field "Proxy.ovpn_password": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VpnStatus(); ok {
		if err := proxy.VpnStatusValidator(v); err != nil {
			return &ValidationError{Name: "vpn_status", err: fmt.Errorf(`ent: validator failed for field "Proxy.vpn_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.VpnExitIP(); ok {
		if err := proxy.VpnExitIPValidator(v); err != nil {
			return &ValidationError{Name: "vpn_exit_ip", err: fmt.Errorf(`ent: validator failed for field "Proxy.vpn_exit_ip": %w`, err)}
		}
	}
	if v, ok := _u.mutation.HealthStatus(); ok {
		if err := proxy.HealthStatusValidator(v); err != nil {
			return &ValidationError{Name: "health_status", err: fmt.Errorf(`ent: validator failed for field "Proxy.health_status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ProxyType(); ok {
		if err := proxy.ProxyTypeValidator(v); err != nil {
			return &ValidationError{Name: "proxy_type", err: fmt.Errorf(`ent: validator failed for field "Proxy.proxy_type": %w`, err)}
		}
	}
	return nil
}

func (_u *ProxyUpdateOne) sqlSave(ctx context.Context) (_node *Proxy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(proxy.Table, proxy.Columns, sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Proxy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxy.FieldID)
		for _, f := range fields {
			if !proxy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != proxy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxy.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxy.FieldDeletedAt, field.TypeTime, value)
	}
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxy.FieldDeletedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxy.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(proxy.FieldProtocol, field.TypeString, value)
	}
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(proxy.FieldHost, field.TypeString, value)
	}
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(proxy.FieldPort, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(proxy.FieldUsername, field.TypeString, value)
	}
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(proxy.FieldUsername, field.TypeString)
	}
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(proxy.FieldPassword, field.TypeString, value)
	}
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(proxy.FieldPassword, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxy.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Region(); ok {
		_spec.SetField(proxy.FieldRegion, field.TypeString, value)
	}
	if _u.mutation.RegionCleared() {
		_spec.ClearField(proxy.FieldRegion, field.TypeString)
	}
	if value, ok := _u.mutation.GroupName(); ok {
		_spec.SetField(proxy.FieldGroupName, field.TypeString, value)
	}
	if _u.mutation.GroupNameCleared() {
		_spec.ClearField(proxy.FieldGroupName, field.TypeString)
	}
	if value, ok := _u.mutation.OvpnConfig(); ok {
		_spec.SetField(proxy.FieldOvpnConfig, field.TypeString, value)
	}
	if _u.mutation.OvpnConfigCleared() {
		_spec.ClearField(proxy.FieldOvpnConfig, field.TypeString)
	}
	if value, ok := _u.mutation.OvpnUsername(); ok {
		_spec.SetField(proxy.FieldOvpnUsername, field.TypeString, value)
	}
	if _u.mutation.OvpnUsernameCleared() {
		_spec.ClearField(proxy.FieldOvpnUsername, field.TypeString)
	}
	if value, ok := _u.mutation.OvpnPassword(); ok {
		_spec.SetField(proxy.FieldOvpnPassword, field.TypeString, value)
	}
	if _u.mutation.OvpnPasswordCleared() {
		_spec.ClearField(proxy.FieldOvpnPassword, field.TypeString)
	}
	if value, ok := _u.mutation.IsDedicated(); ok {
		_spec.SetField(proxy.FieldIsDedicated, field.TypeBool, value)
	}
	if value, ok := _u.mutation.VpnStatus(); ok {
		_spec.SetField(proxy.FieldVpnStatus, field.TypeString, value)
	}
	if _u.mutation.VpnStatusCleared() {
		_spec.ClearField(proxy.FieldVpnStatus, field.TypeString)
	}
	if value, ok := _u.mutation.VpnExitIP(); ok {
		_spec.SetField(proxy.FieldVpnExitIP, field.TypeString, value)
	}
	if _u.mutation.VpnExitIPCleared() {
		_spec.ClearField(proxy.FieldVpnExitIP, field.TypeString)
	}
	if value, ok := _u.mutation.HealthStatus(); ok {
		_spec.SetField(proxy.FieldHealthStatus, field.TypeString, value)
	}
	if _u.mutation.HealthStatusCleared() {
		_spec.ClearField(proxy.FieldHealthStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LatencyMs(); ok {
		_spec.SetField(proxy.FieldLatencyMs, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLatencyMs(); ok {
		_spec.AddField(proxy.FieldLatencyMs, field.TypeInt, value)
	}
	if _u.mutation.LatencyMsCleared() {
		_spec.ClearField(proxy.FieldLatencyMs, field.TypeInt)
	}
	if value, ok := _u.mutation.LastHealthAt(); ok {
		_spec.SetField(proxy.FieldLastHealthAt, field.TypeTime, value)
	}
	if _u.mutation.LastHealthAtCleared() {
		_spec.ClearField(proxy.FieldLastHealthAt, field.TypeTime)
	}
	if value, ok := _u.mutation.HealthCheckFailures(); ok {
		_spec.SetField(proxy.FieldHealthCheckFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHealthCheckFailures(); ok {
		_spec.AddField(proxy.FieldHealthCheckFailures, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ProxyType(); ok {
		_spec.SetField(proxy.FieldProxyType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Priority(); ok {
		_spec.SetField(proxy.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPriority(); ok {
		_spec.AddField(proxy.FieldPriority, field.TypeInt, value)
	}
	if value, ok := _u.mutation.ConfigVersion(); ok {
		_spec.SetField(proxy.FieldConfigVersion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedConfigVersion(); ok {
		_spec.AddField(proxy.FieldConfigVersion, field.TypeInt, value)
	}
	if _u.mutation.ConfigVersionCleared() {
		_spec.ClearField(proxy.FieldConfigVersion, field.TypeInt)
	}
	if value, ok := _u.mutation.LastConnectedAt(); ok {
		_spec.SetField(proxy.FieldLastConnectedAt, field.TypeTime, value)
	}
	if _u.mutation.LastConnectedAtCleared() {
		_spec.ClearField(proxy.FieldLastConnectedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ConfigStale(); ok {
		_spec.SetField(proxy.FieldConfigStale, field.TypeBool, value)
	}
	if _u.mutation.ConfigStaleCleared() {
		_spec.ClearField(proxy.FieldConfigStale, field.TypeBool)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Proxy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
