// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/rechargepackage"
)

// RechargePackageUpdate is the builder for updating RechargePackage entities.
type RechargePackageUpdate struct {
	config
	hooks    []Hook
	mutation *RechargePackageMutation
}

// Where appends a list predicates to the RechargePackageUpdate builder.
func (_u *RechargePackageUpdate) Where(ps ...predicate.RechargePackage) *RechargePackageUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAmountCny sets the "amount_cny" field.
func (_u *RechargePackageUpdate) SetAmountCny(v float64) *RechargePackageUpdate {
	_u.mutation.ResetAmountCny()
	_u.mutation.SetAmountCny(v)
	return _u
}

// SetNillableAmountCny sets the "amount_cny" field if the given value is not nil.
func (_u *RechargePackageUpdate) SetNillableAmountCny(v *float64) *RechargePackageUpdate {
	if v != nil {
		_u.SetAmountCny(*v)
	}
	return _u
}

// AddAmountCny adds value to the "amount_cny" field.
func (_u *RechargePackageUpdate) AddAmountCny(v float64) *RechargePackageUpdate {
	_u.mutation.AddAmountCny(v)
	return _u
}

// SetBonusRate sets the "bonus_rate" field.
func (_u *RechargePackageUpdate) SetBonusRate(v float64) *RechargePackageUpdate {
	_u.mutation.ResetBonusRate()
	_u.mutation.SetBonusRate(v)
	return _u
}

// SetNillableBonusRate sets the "bonus_rate" field if the given value is not nil.
func (_u *RechargePackageUpdate) SetNillableBonusRate(v *float64) *RechargePackageUpdate {
	if v != nil {
		_u.SetBonusRate(*v)
	}
	return _u
}

// AddBonusRate adds value to the "bonus_rate" field.
func (_u *RechargePackageUpdate) AddBonusRate(v float64) *RechargePackageUpdate {
	_u.mutation.AddBonusRate(v)
	return _u
}

// SetBonusFixed sets the "bonus_fixed" field.
func (_u *RechargePackageUpdate) SetBonusFixed(v float64) *RechargePackageUpdate {
	_u.mutation.ResetBonusFixed()
	_u.mutation.SetBonusFixed(v)
	return _u
}

// SetNillableBonusFixed sets the "bonus_fixed" field if the given value is not nil.
func (_u *RechargePackageUpdate) SetNillableBonusFixed(v *float64) *RechargePackageUpdate {
	if v != nil {
		_u.SetBonusFixed(*v)
	}
	return _u
}

// AddBonusFixed adds value to the "bonus_fixed" field.
func (_u *RechargePackageUpdate) AddBonusFixed(v float64) *RechargePackageUpdate {
	_u.mutation.AddBonusFixed(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *RechargePackageUpdate) SetLabel(v string) *RechargePackageUpdate {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *RechargePackageUpdate) SetNillableLabel(v *string) *RechargePackageUpdate {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *RechargePackageUpdate) ClearLabel() *RechargePackageUpdate {
	_u.mutation.ClearLabel()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *RechargePackageUpdate) SetIsActive(v bool) *RechargePackageUpdate {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *RechargePackageUpdate) SetNillableIsActive(v *bool) *RechargePackageUpdate {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *RechargePackageUpdate) SetSortOrder(v int) *RechargePackageUpdate {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *RechargePackageUpdate) SetNillableSortOrder(v *int) *RechargePackageUpdate {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *RechargePackageUpdate) AddSortOrder(v int) *RechargePackageUpdate {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargePackageUpdate) SetUpdatedAt(v time.Time) *RechargePackageUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RechargePackageMutation object of the builder.
func (_u *RechargePackageUpdate) Mutation() *RechargePackageMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RechargePackageUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargePackageUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RechargePackageUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargePackageUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RechargePackageUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rechargepackage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargePackageUpdate) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := rechargepackage.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "RechargePackage.label": %w`, err)}
		}
	}
	return nil
}

func (_u *RechargePackageUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargepackage.Table, rechargepackage.Columns, sqlgraph.NewFieldSpec(rechargepackage.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AmountCny(); ok {
		_spec.SetField(rechargepackage.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCny(); ok {
		_spec.AddField(rechargepackage.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BonusRate(); ok {
		_spec.SetField(rechargepackage.FieldBonusRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusRate(); ok {
		_spec.AddField(rechargepackage.FieldBonusRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BonusFixed(); ok {
		_spec.SetField(rechargepackage.FieldBonusFixed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusFixed(); ok {
		_spec.AddField(rechargepackage.FieldBonusFixed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(rechargepackage.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(rechargepackage.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(rechargepackage.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(rechargepackage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(rechargepackage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargepackage.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargepackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RechargePackageUpdateOne is the builder for updating a single RechargePackage entity.
type RechargePackageUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RechargePackageMutation
}

// SetAmountCny sets the "amount_cny" field.
func (_u *RechargePackageUpdateOne) SetAmountCny(v float64) *RechargePackageUpdateOne {
	_u.mutation.ResetAmountCny()
	_u.mutation.SetAmountCny(v)
	return _u
}

// SetNillableAmountCny sets the "amount_cny" field if the given value is not nil.
func (_u *RechargePackageUpdateOne) SetNillableAmountCny(v *float64) *RechargePackageUpdateOne {
	if v != nil {
		_u.SetAmountCny(*v)
	}
	return _u
}

// AddAmountCny adds value to the "amount_cny" field.
func (_u *RechargePackageUpdateOne) AddAmountCny(v float64) *RechargePackageUpdateOne {
	_u.mutation.AddAmountCny(v)
	return _u
}

// SetBonusRate sets the "bonus_rate" field.
func (_u *RechargePackageUpdateOne) SetBonusRate(v float64) *RechargePackageUpdateOne {
	_u.mutation.ResetBonusRate()
	_u.mutation.SetBonusRate(v)
	return _u
}

// SetNillableBonusRate sets the "bonus_rate" field if the given value is not nil.
func (_u *RechargePackageUpdateOne) SetNillableBonusRate(v *float64) *RechargePackageUpdateOne {
	if v != nil {
		_u.SetBonusRate(*v)
	}
	return _u
}

// AddBonusRate adds value to the "bonus_rate" field.
func (_u *RechargePackageUpdateOne) AddBonusRate(v float64) *RechargePackageUpdateOne {
	_u.mutation.AddBonusRate(v)
	return _u
}

// SetBonusFixed sets the "bonus_fixed" field.
func (_u *RechargePackageUpdateOne) SetBonusFixed(v float64) *RechargePackageUpdateOne {
	_u.mutation.ResetBonusFixed()
	_u.mutation.SetBonusFixed(v)
	return _u
}

// SetNillableBonusFixed sets the "bonus_fixed" field if the given value is not nil.
func (_u *RechargePackageUpdateOne) SetNillableBonusFixed(v *float64) *RechargePackageUpdateOne {
	if v != nil {
		_u.SetBonusFixed(*v)
	}
	return _u
}

// AddBonusFixed adds value to the "bonus_fixed" field.
func (_u *RechargePackageUpdateOne) AddBonusFixed(v float64) *RechargePackageUpdateOne {
	_u.mutation.AddBonusFixed(v)
	return _u
}

// SetLabel sets the "label" field.
func (_u *RechargePackageUpdateOne) SetLabel(v string) *RechargePackageUpdateOne {
	_u.mutation.SetLabel(v)
	return _u
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_u *RechargePackageUpdateOne) SetNillableLabel(v *string) *RechargePackageUpdateOne {
	if v != nil {
		_u.SetLabel(*v)
	}
	return _u
}

// ClearLabel clears the value of the "label" field.
func (_u *RechargePackageUpdateOne) ClearLabel() *RechargePackageUpdateOne {
	_u.mutation.ClearLabel()
	return _u
}

// SetIsActive sets the "is_active" field.
func (_u *RechargePackageUpdateOne) SetIsActive(v bool) *RechargePackageUpdateOne {
	_u.mutation.SetIsActive(v)
	return _u
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_u *RechargePackageUpdateOne) SetNillableIsActive(v *bool) *RechargePackageUpdateOne {
	if v != nil {
		_u.SetIsActive(*v)
	}
	return _u
}

// SetSortOrder sets the "sort_order" field.
func (_u *RechargePackageUpdateOne) SetSortOrder(v int) *RechargePackageUpdateOne {
	_u.mutation.ResetSortOrder()
	_u.mutation.SetSortOrder(v)
	return _u
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_u *RechargePackageUpdateOne) SetNillableSortOrder(v *int) *RechargePackageUpdateOne {
	if v != nil {
		_u.SetSortOrder(*v)
	}
	return _u
}

// AddSortOrder adds value to the "sort_order" field.
func (_u *RechargePackageUpdateOne) AddSortOrder(v int) *RechargePackageUpdateOne {
	_u.mutation.AddSortOrder(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RechargePackageUpdateOne) SetUpdatedAt(v time.Time) *RechargePackageUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the RechargePackageMutation object of the builder.
func (_u *RechargePackageUpdateOne) Mutation() *RechargePackageMutation {
	return _u.mutation
}

// Where appends a list predicates to the RechargePackageUpdate builder.
func (_u *RechargePackageUpdateOne) Where(ps ...predicate.RechargePackage) *RechargePackageUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RechargePackageUpdateOne) Select(field string, fields ...string) *RechargePackageUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RechargePackage entity.
func (_u *RechargePackageUpdateOne) Save(ctx context.Context) (*RechargePackage, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RechargePackageUpdateOne) SaveX(ctx context.Context) *RechargePackage {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RechargePackageUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RechargePackageUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RechargePackageUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := rechargepackage.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RechargePackageUpdateOne) check() error {
	if v, ok := _u.mutation.Label(); ok {
		if err := rechargepackage.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "RechargePackage.label": %w`, err)}
		}
	}
	return nil
}

func (_u *RechargePackageUpdateOne) sqlSave(ctx context.Context) (_node *RechargePackage, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(rechargepackage.Table, rechargepackage.Columns, sqlgraph.NewFieldSpec(rechargepackage.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RechargePackage.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, rechargepackage.FieldID)
		for _, f := range fields {
			if !rechargepackage.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != rechargepackage.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AmountCny(); ok {
		_spec.SetField(rechargepackage.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmountCny(); ok {
		_spec.AddField(rechargepackage.FieldAmountCny, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BonusRate(); ok {
		_spec.SetField(rechargepackage.FieldBonusRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusRate(); ok {
		_spec.AddField(rechargepackage.FieldBonusRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.BonusFixed(); ok {
		_spec.SetField(rechargepackage.FieldBonusFixed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBonusFixed(); ok {
		_spec.AddField(rechargepackage.FieldBonusFixed, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Label(); ok {
		_spec.SetField(rechargepackage.FieldLabel, field.TypeString, value)
	}
	if _u.mutation.LabelCleared() {
		_spec.ClearField(rechargepackage.FieldLabel, field.TypeString)
	}
	if value, ok := _u.mutation.IsActive(); ok {
		_spec.SetField(rechargepackage.FieldIsActive, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SortOrder(); ok {
		_spec.SetField(rechargepackage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSortOrder(); ok {
		_spec.AddField(rechargepackage.FieldSortOrder, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargepackage.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &RechargePackage{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{rechargepackage.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
