// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/rechargepackage"
)

// RechargePackage is the model entity for the RechargePackage schema.
type RechargePackage struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// BonusRate holds the value of the "bonus_rate" field.
	BonusRate float64 `json:"bonus_rate,omitempty"`
	// BonusFixed holds the value of the "bonus_fixed" field.
	BonusFixed float64 `json:"bonus_fixed,omitempty"`
	// Label holds the value of the "label" field.
	Label *string `json:"label,omitempty"`
	// IsActive holds the value of the "is_active" field.
	IsActive bool `json:"is_active,omitempty"`
	// SortOrder holds the value of the "sort_order" field.
	SortOrder int `json:"sort_order,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RechargePackage) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case rechargepackage.FieldIsActive:
			values[i] = new(sql.NullBool)
		case rechargepackage.FieldAmount, rechargepackage.FieldBonusRate, rechargepackage.FieldBonusFixed:
			values[i] = new(sql.NullFloat64)
		case rechargepackage.FieldID, rechargepackage.FieldSortOrder:
			values[i] = new(sql.NullInt64)
		case rechargepackage.FieldLabel:
			values[i] = new(sql.NullString)
		case rechargepackage.FieldCreatedAt, rechargepackage.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RechargePackage fields.
func (_m *RechargePackage) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case rechargepackage.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case rechargepackage.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case rechargepackage.FieldBonusRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_rate", values[i])
			} else if value.Valid {
				_m.BonusRate = value.Float64
			}
		case rechargepackage.FieldBonusFixed:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field bonus_fixed", values[i])
			} else if value.Valid {
				_m.BonusFixed = value.Float64
			}
		case rechargepackage.FieldLabel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field label", values[i])
			} else if value.Valid {
				_m.Label = new(string)
				*_m.Label = value.String
			}
		case rechargepackage.FieldIsActive:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_active", values[i])
			} else if value.Valid {
				_m.IsActive = value.Bool
			}
		case rechargepackage.FieldSortOrder:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field sort_order", values[i])
			} else if value.Valid {
				_m.SortOrder = int(value.Int64)
			}
		case rechargepackage.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case rechargepackage.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RechargePackage.
// This includes values selected through modifiers, order, etc.
func (_m *RechargePackage) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this RechargePackage.
// Note that you need to call RechargePackage.Unwrap() before calling this method if this RechargePackage
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RechargePackage) Update() *RechargePackageUpdateOne {
	return NewRechargePackageClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RechargePackage entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RechargePackage) Unwrap() *RechargePackage {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RechargePackage is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RechargePackage) String() string {
	var builder strings.Builder
	builder.WriteString("RechargePackage(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("bonus_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusRate))
	builder.WriteString(", ")
	builder.WriteString("bonus_fixed=")
	builder.WriteString(fmt.Sprintf("%v", _m.BonusFixed))
	builder.WriteString(", ")
	if v := _m.Label; v != nil {
		builder.WriteString("label=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("is_active=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsActive))
	builder.WriteString(", ")
	builder.WriteString("sort_order=")
	builder.WriteString(fmt.Sprintf("%v", _m.SortOrder))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RechargePackages is a parsable slice of RechargePackage.
type RechargePackages []*RechargePackage
