// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/rechargepackage"
)

// RechargePackageCreate is the builder for creating a RechargePackage entity.
type RechargePackageCreate struct {
	config
	mutation *RechargePackageMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetAmountCny sets the "amount_cny" field.
func (_c *RechargePackageCreate) SetAmountCny(v float64) *RechargePackageCreate {
	_c.mutation.SetAmountCny(v)
	return _c
}

// SetBonusRate sets the "bonus_rate" field.
func (_c *RechargePackageCreate) SetBonusRate(v float64) *RechargePackageCreate {
	_c.mutation.SetBonusRate(v)
	return _c
}

// SetNillableBonusRate sets the "bonus_rate" field if the given value is not nil.
func (_c *RechargePackageCreate) SetNillableBonusRate(v *float64) *RechargePackageCreate {
	if v != nil {
		_c.SetBonusRate(*v)
	}
	return _c
}

// SetBonusFixed sets the "bonus_fixed" field.
func (_c *RechargePackageCreate) SetBonusFixed(v float64) *RechargePackageCreate {
	_c.mutation.SetBonusFixed(v)
	return _c
}

// SetNillableBonusFixed sets the "bonus_fixed" field if the given value is not nil.
func (_c *RechargePackageCreate) SetNillableBonusFixed(v *float64) *RechargePackageCreate {
	if v != nil {
		_c.SetBonusFixed(*v)
	}
	return _c
}

// SetLabel sets the "label" field.
func (_c *RechargePackageCreate) SetLabel(v string) *RechargePackageCreate {
	_c.mutation.SetLabel(v)
	return _c
}

// SetNillableLabel sets the "label" field if the given value is not nil.
func (_c *RechargePackageCreate) SetNillableLabel(v *string) *RechargePackageCreate {
	if v != nil {
		_c.SetLabel(*v)
	}
	return _c
}

// SetIsActive sets the "is_active" field.
func (_c *RechargePackageCreate) SetIsActive(v bool) *RechargePackageCreate {
	_c.mutation.SetIsActive(v)
	return _c
}

// SetNillableIsActive sets the "is_active" field if the given value is not nil.
func (_c *RechargePackageCreate) SetNillableIsActive(v *bool) *RechargePackageCreate {
	if v != nil {
		_c.SetIsActive(*v)
	}
	return _c
}

// SetSortOrder sets the "sort_order" field.
func (_c *RechargePackageCreate) SetSortOrder(v int) *RechargePackageCreate {
	_c.mutation.SetSortOrder(v)
	return _c
}

// SetNillableSortOrder sets the "sort_order" field if the given value is not nil.
func (_c *RechargePackageCreate) SetNillableSortOrder(v *int) *RechargePackageCreate {
	if v != nil {
		_c.SetSortOrder(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *RechargePackageCreate) SetCreatedAt(v time.Time) *RechargePackageCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *RechargePackageCreate) SetNillableCreatedAt(v *time.Time) *RechargePackageCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *RechargePackageCreate) SetUpdatedAt(v time.Time) *RechargePackageCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *RechargePackageCreate) SetNillableUpdatedAt(v *time.Time) *RechargePackageCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the RechargePackageMutation object of the builder.
func (_c *RechargePackageCreate) Mutation() *RechargePackageMutation {
	return _c.mutation
}

// Save creates the RechargePackage in the database.
func (_c *RechargePackageCreate) Save(ctx context.Context) (*RechargePackage, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *RechargePackageCreate) SaveX(ctx context.Context) *RechargePackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargePackageCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargePackageCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *RechargePackageCreate) defaults() {
	if _, ok := _c.mutation.BonusRate(); !ok {
		v := rechargepackage.DefaultBonusRate
		_c.mutation.SetBonusRate(v)
	}
	if _, ok := _c.mutation.BonusFixed(); !ok {
		v := rechargepackage.DefaultBonusFixed
		_c.mutation.SetBonusFixed(v)
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		v := rechargepackage.DefaultIsActive
		_c.mutation.SetIsActive(v)
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		v := rechargepackage.DefaultSortOrder
		_c.mutation.SetSortOrder(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := rechargepackage.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := rechargepackage.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *RechargePackageCreate) check() error {
	if _, ok := _c.mutation.AmountCny(); !ok {
		return &ValidationError{Name: "amount_cny", err: errors.New(`ent: missing required field "RechargePackage.amount_cny"`)}
	}
	if _, ok := _c.mutation.BonusRate(); !ok {
		return &ValidationError{Name: "bonus_rate", err: errors.New(`ent: missing required field "RechargePackage.bonus_rate"`)}
	}
	if _, ok := _c.mutation.BonusFixed(); !ok {
		return &ValidationError{Name: "bonus_fixed", err: errors.New(`ent: missing required field "RechargePackage.bonus_fixed"`)}
	}
	if v, ok := _c.mutation.Label(); ok {
		if err := rechargepackage.LabelValidator(v); err != nil {
			return &ValidationError{Name: "label", err: fmt.Errorf(`ent: validator failed for field "RechargePackage.label": %w`, err)}
		}
	}
	if _, ok := _c.mutation.IsActive(); !ok {
		return &ValidationError{Name: "is_active", err: errors.New(`ent: missing required field "RechargePackage.is_active"`)}
	}
	if _, ok := _c.mutation.SortOrder(); !ok {
		return &ValidationError{Name: "sort_order", err: errors.New(`ent: missing required field "RechargePackage.sort_order"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "RechargePackage.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "RechargePackage.updated_at"`)}
	}
	return nil
}

func (_c *RechargePackageCreate) sqlSave(ctx context.Context) (*RechargePackage, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *RechargePackageCreate) createSpec() (*RechargePackage, *sqlgraph.CreateSpec) {
	var (
		_node = &RechargePackage{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(rechargepackage.Table, sqlgraph.NewFieldSpec(rechargepackage.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.AmountCny(); ok {
		_spec.SetField(rechargepackage.FieldAmountCny, field.TypeFloat64, value)
		_node.AmountCny = value
	}
	if value, ok := _c.mutation.BonusRate(); ok {
		_spec.SetField(rechargepackage.FieldBonusRate, field.TypeFloat64, value)
		_node.BonusRate = value
	}
	if value, ok := _c.mutation.BonusFixed(); ok {
		_spec.SetField(rechargepackage.FieldBonusFixed, field.TypeFloat64, value)
		_node.BonusFixed = value
	}
	if value, ok := _c.mutation.Label(); ok {
		_spec.SetField(rechargepackage.FieldLabel, field.TypeString, value)
		_node.Label = &value
	}
	if value, ok := _c.mutation.IsActive(); ok {
		_spec.SetField(rechargepackage.FieldIsActive, field.TypeBool, value)
		_node.IsActive = value
	}
	if value, ok := _c.mutation.SortOrder(); ok {
		_spec.SetField(rechargepackage.FieldSortOrder, field.TypeInt, value)
		_node.SortOrder = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(rechargepackage.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(rechargepackage.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargePackage.Create().
//		SetAmountCny(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargePackageUpsert) {
//			SetAmountCny(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargePackageCreate) OnConflict(opts ...sql.ConflictOption) *RechargePackageUpsertOne {
	_c.conflict = opts
	return &RechargePackageUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargePackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargePackageCreate) OnConflictColumns(columns ...string) *RechargePackageUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargePackageUpsertOne{
		create: _c,
	}
}

type (
	// RechargePackageUpsertOne is the builder for "upsert"-ing
	//  one RechargePackage node.
	RechargePackageUpsertOne struct {
		create *RechargePackageCreate
	}

	// RechargePackageUpsert is the "OnConflict" setter.
	RechargePackageUpsert struct {
		*sql.UpdateSet
	}
)

// SetAmountCny sets the "amount_cny" field.
func (u *RechargePackageUpsert) SetAmountCny(v float64) *RechargePackageUpsert {
	u.Set(rechargepackage.FieldAmountCny, v)
	return u
}

// UpdateAmountCny sets the "amount_cny" field to the value that was provided on create.
func (u *RechargePackageUpsert) UpdateAmountCny() *RechargePackageUpsert {
	u.SetExcluded(rechargepackage.FieldAmountCny)
	return u
}

// AddAmountCny adds v to the "amount_cny" field.
func (u *RechargePackageUpsert) AddAmountCny(v float64) *RechargePackageUpsert {
	u.Add(rechargepackage.FieldAmountCny, v)
	return u
}

// SetBonusRate sets the "bonus_rate" field.
func (u *RechargePackageUpsert) SetBonusRate(v float64) *RechargePackageUpsert {
	u.Set(rechargepackage.FieldBonusRate, v)
	return u
}

// UpdateBonusRate sets the "bonus_rate" field to the value that was provided on create.
func (u *RechargePackageUpsert) UpdateBonusRate() *RechargePackageUpsert {
	u.SetExcluded(rechargepackage.FieldBonusRate)
	return u
}

// AddBonusRate adds v to the "bonus_rate" field.
func (u *RechargePackageUpsert) AddBonusRate(v float64) *RechargePackageUpsert {
	u.Add(rechargepackage.FieldBonusRate, v)
	return u
}

// SetBonusFixed sets the "bonus_fixed" field.
func (u *RechargePackageUpsert) SetBonusFixed(v float64) *RechargePackageUpsert {
	u.Set(rechargepackage.FieldBonusFixed, v)
	return u
}

// UpdateBonusFixed sets the "bonus_fixed" field to the value that was provided on create.
func (u *RechargePackageUpsert) UpdateBonusFixed() *RechargePackageUpsert {
	u.SetExcluded(rechargepackage.FieldBonusFixed)
	return u
}

// AddBonusFixed adds v to the "bonus_fixed" field.
func (u *RechargePackageUpsert) AddBonusFixed(v float64) *RechargePackageUpsert {
	u.Add(rechargepackage.FieldBonusFixed, v)
	return u
}

// SetLabel sets the "label" field.
func (u *RechargePackageUpsert) SetLabel(v string) *RechargePackageUpsert {
	u.Set(rechargepackage.FieldLabel, v)
	return u
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *RechargePackageUpsert) UpdateLabel() *RechargePackageUpsert {
	u.SetExcluded(rechargepackage.FieldLabel)
	return u
}

// ClearLabel clears the value of the "label" field.
func (u *RechargePackageUpsert) ClearLabel() *RechargePackageUpsert {
	u.SetNull(rechargepackage.FieldLabel)
	return u
}

// SetIsActive sets the "is_active" field.
func (u *RechargePackageUpsert) SetIsActive(v bool) *RechargePackageUpsert {
	u.Set(rechargepackage.FieldIsActive, v)
	return u
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *RechargePackageUpsert) UpdateIsActive() *RechargePackageUpsert {
	u.SetExcluded(rechargepackage.FieldIsActive)
	return u
}

// SetSortOrder sets the "sort_order" field.
func (u *RechargePackageUpsert) SetSortOrder(v int) *RechargePackageUpsert {
	u.Set(rechargepackage.FieldSortOrder, v)
	return u
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *RechargePackageUpsert) UpdateSortOrder() *RechargePackageUpsert {
	u.SetExcluded(rechargepackage.FieldSortOrder)
	return u
}

// AddSortOrder adds v to the "sort_order" field.
func (u *RechargePackageUpsert) AddSortOrder(v int) *RechargePackageUpsert {
	u.Add(rechargepackage.FieldSortOrder, v)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargePackageUpsert) SetUpdatedAt(v time.Time) *RechargePackageUpsert {
	u.Set(rechargepackage.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargePackageUpsert) UpdateUpdatedAt() *RechargePackageUpsert {
	u.SetExcluded(rechargepackage.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.RechargePackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargePackageUpsertOne) UpdateNewValues() *RechargePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(rechargepackage.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargePackage.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *RechargePackageUpsertOne) Ignore() *RechargePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargePackageUpsertOne) DoNothing() *RechargePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargePackageCreate.OnConflict
// documentation for more info.
func (u *RechargePackageUpsertOne) Update(set func(*RechargePackageUpsert)) *RechargePackageUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargePackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetAmountCny sets the "amount_cny" field.
func (u *RechargePackageUpsertOne) SetAmountCny(v float64) *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetAmountCny(v)
	})
}

// AddAmountCny adds v to the "amount_cny" field.
func (u *RechargePackageUpsertOne) AddAmountCny(v float64) *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.AddAmountCny(v)
	})
}

// UpdateAmountCny sets the "amount_cny" field to the value that was provided on create.
func (u *RechargePackageUpsertOne) UpdateAmountCny() *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateAmountCny()
	})
}

// SetBonusRate sets the "bonus_rate" field.
func (u *RechargePackageUpsertOne) SetBonusRate(v float64) *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetBonusRate(v)
	})
}

// AddBonusRate adds v to the "bonus_rate" field.
func (u *RechargePackageUpsertOne) AddBonusRate(v float64) *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.AddBonusRate(v)
	})
}

// UpdateBonusRate sets the "bonus_rate" field to the value that was provided on create.
func (u *RechargePackageUpsertOne) UpdateBonusRate() *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateBonusRate()
	})
}

// SetBonusFixed sets the "bonus_fixed" field.
func (u *RechargePackageUpsertOne) SetBonusFixed(v float64) *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetBonusFixed(v)
	})
}

// AddBonusFixed adds v to the "bonus_fixed" field.
func (u *RechargePackageUpsertOne) AddBonusFixed(v float64) *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.AddBonusFixed(v)
	})
}

// UpdateBonusFixed sets the "bonus_fixed" field to the value that was provided on create.
func (u *RechargePackageUpsertOne) UpdateBonusFixed() *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateBonusFixed()
	})
}

// SetLabel sets the "label" field.
func (u *RechargePackageUpsertOne) SetLabel(v string) *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *RechargePackageUpsertOne) UpdateLabel() *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateLabel()
	})
}

// ClearLabel clears the value of the "label" field.
func (u *RechargePackageUpsertOne) ClearLabel() *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.ClearLabel()
	})
}

// SetIsActive sets the "is_active" field.
func (u *RechargePackageUpsertOne) SetIsActive(v bool) *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *RechargePackageUpsertOne) UpdateIsActive() *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateIsActive()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *RechargePackageUpsertOne) SetSortOrder(v int) *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *RechargePackageUpsertOne) AddSortOrder(v int) *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *RechargePackageUpsertOne) UpdateSortOrder() *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargePackageUpsertOne) SetUpdatedAt(v time.Time) *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargePackageUpsertOne) UpdateUpdatedAt() *RechargePackageUpsertOne {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RechargePackageUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargePackageCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargePackageUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *RechargePackageUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *RechargePackageUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// RechargePackageCreateBulk is the builder for creating many RechargePackage entities in bulk.
type RechargePackageCreateBulk struct {
	config
	err      error
	builders []*RechargePackageCreate
	conflict []sql.ConflictOption
}

// Save creates the RechargePackage entities in the database.
func (_c *RechargePackageCreateBulk) Save(ctx context.Context) ([]*RechargePackage, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*RechargePackage, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*RechargePackageMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *RechargePackageCreateBulk) SaveX(ctx context.Context) []*RechargePackage {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *RechargePackageCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *RechargePackageCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.RechargePackage.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.RechargePackageUpsert) {
//			SetAmountCny(v+v).
//		}).
//		Exec(ctx)
func (_c *RechargePackageCreateBulk) OnConflict(opts ...sql.ConflictOption) *RechargePackageUpsertBulk {
	_c.conflict = opts
	return &RechargePackageUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.RechargePackage.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *RechargePackageCreateBulk) OnConflictColumns(columns ...string) *RechargePackageUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &RechargePackageUpsertBulk{
		create: _c,
	}
}

// RechargePackageUpsertBulk is the builder for "upsert"-ing
// a bulk of RechargePackage nodes.
type RechargePackageUpsertBulk struct {
	create *RechargePackageCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.RechargePackage.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *RechargePackageUpsertBulk) UpdateNewValues() *RechargePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(rechargepackage.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.RechargePackage.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *RechargePackageUpsertBulk) Ignore() *RechargePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *RechargePackageUpsertBulk) DoNothing() *RechargePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the RechargePackageCreateBulk.OnConflict
// documentation for more info.
func (u *RechargePackageUpsertBulk) Update(set func(*RechargePackageUpsert)) *RechargePackageUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&RechargePackageUpsert{UpdateSet: update})
	}))
	return u
}

// SetAmountCny sets the "amount_cny" field.
func (u *RechargePackageUpsertBulk) SetAmountCny(v float64) *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetAmountCny(v)
	})
}

// AddAmountCny adds v to the "amount_cny" field.
func (u *RechargePackageUpsertBulk) AddAmountCny(v float64) *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.AddAmountCny(v)
	})
}

// UpdateAmountCny sets the "amount_cny" field to the value that was provided on create.
func (u *RechargePackageUpsertBulk) UpdateAmountCny() *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateAmountCny()
	})
}

// SetBonusRate sets the "bonus_rate" field.
func (u *RechargePackageUpsertBulk) SetBonusRate(v float64) *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetBonusRate(v)
	})
}

// AddBonusRate adds v to the "bonus_rate" field.
func (u *RechargePackageUpsertBulk) AddBonusRate(v float64) *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.AddBonusRate(v)
	})
}

// UpdateBonusRate sets the "bonus_rate" field to the value that was provided on create.
func (u *RechargePackageUpsertBulk) UpdateBonusRate() *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateBonusRate()
	})
}

// SetBonusFixed sets the "bonus_fixed" field.
func (u *RechargePackageUpsertBulk) SetBonusFixed(v float64) *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetBonusFixed(v)
	})
}

// AddBonusFixed adds v to the "bonus_fixed" field.
func (u *RechargePackageUpsertBulk) AddBonusFixed(v float64) *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.AddBonusFixed(v)
	})
}

// UpdateBonusFixed sets the "bonus_fixed" field to the value that was provided on create.
func (u *RechargePackageUpsertBulk) UpdateBonusFixed() *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateBonusFixed()
	})
}

// SetLabel sets the "label" field.
func (u *RechargePackageUpsertBulk) SetLabel(v string) *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetLabel(v)
	})
}

// UpdateLabel sets the "label" field to the value that was provided on create.
func (u *RechargePackageUpsertBulk) UpdateLabel() *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateLabel()
	})
}

// ClearLabel clears the value of the "label" field.
func (u *RechargePackageUpsertBulk) ClearLabel() *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.ClearLabel()
	})
}

// SetIsActive sets the "is_active" field.
func (u *RechargePackageUpsertBulk) SetIsActive(v bool) *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetIsActive(v)
	})
}

// UpdateIsActive sets the "is_active" field to the value that was provided on create.
func (u *RechargePackageUpsertBulk) UpdateIsActive() *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateIsActive()
	})
}

// SetSortOrder sets the "sort_order" field.
func (u *RechargePackageUpsertBulk) SetSortOrder(v int) *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetSortOrder(v)
	})
}

// AddSortOrder adds v to the "sort_order" field.
func (u *RechargePackageUpsertBulk) AddSortOrder(v int) *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.AddSortOrder(v)
	})
}

// UpdateSortOrder sets the "sort_order" field to the value that was provided on create.
func (u *RechargePackageUpsertBulk) UpdateSortOrder() *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateSortOrder()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *RechargePackageUpsertBulk) SetUpdatedAt(v time.Time) *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *RechargePackageUpsertBulk) UpdateUpdatedAt() *RechargePackageUpsertBulk {
	return u.Update(func(s *RechargePackageUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *RechargePackageUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the RechargePackageCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for RechargePackageCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *RechargePackageUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
