// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
)

// ReferralCommissionCreate is the builder for creating a ReferralCommission entity.
type ReferralCommissionCreate struct {
	config
	mutation *ReferralCommissionMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviterID sets the "inviter_id" field.
func (_c *ReferralCommissionCreate) SetInviterID(v int64) *ReferralCommissionCreate {
	_c.mutation.SetInviterID(v)
	return _c
}

// SetInviteeID sets the "invitee_id" field.
func (_c *ReferralCommissionCreate) SetInviteeID(v int64) *ReferralCommissionCreate {
	_c.mutation.SetInviteeID(v)
	return _c
}

// SetOrderID sets the "order_id" field.
func (_c *ReferralCommissionCreate) SetOrderID(v int64) *ReferralCommissionCreate {
	_c.mutation.SetOrderID(v)
	return _c
}

// SetOrderAmountUsd sets the "order_amount_usd" field.
func (_c *ReferralCommissionCreate) SetOrderAmountUsd(v float64) *ReferralCommissionCreate {
	_c.mutation.SetOrderAmountUsd(v)
	return _c
}

// SetCommissionRate sets the "commission_rate" field.
func (_c *ReferralCommissionCreate) SetCommissionRate(v float64) *ReferralCommissionCreate {
	_c.mutation.SetCommissionRate(v)
	return _c
}

// SetCommissionAmount sets the "commission_amount" field.
func (_c *ReferralCommissionCreate) SetCommissionAmount(v float64) *ReferralCommissionCreate {
	_c.mutation.SetCommissionAmount(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *ReferralCommissionCreate) SetStatus(v string) *ReferralCommissionCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableStatus(v *string) *ReferralCommissionCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSettledAt sets the "settled_at" field.
func (_c *ReferralCommissionCreate) SetSettledAt(v time.Time) *ReferralCommissionCreate {
	_c.mutation.SetSettledAt(v)
	return _c
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableSettledAt(v *time.Time) *ReferralCommissionCreate {
	if v != nil {
		_c.SetSettledAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReferralCommissionCreate) SetCreatedAt(v time.Time) *ReferralCommissionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReferralCommissionCreate) SetNillableCreatedAt(v *time.Time) *ReferralCommissionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_c *ReferralCommissionCreate) Mutation() *ReferralCommissionMutation {
	return _c.mutation
}

// Save creates the ReferralCommission in the database.
func (_c *ReferralCommissionCreate) Save(ctx context.Context) (*ReferralCommission, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferralCommissionCreate) SaveX(ctx context.Context) *ReferralCommission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCommissionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCommissionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReferralCommissionCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := referralcommission.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := referralcommission.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferralCommissionCreate) check() error {
	if _, ok := _c.mutation.InviterID(); !ok {
		return &ValidationError{Name: "inviter_id", err: errors.New(`ent: missing required field "ReferralCommission.inviter_id"`)}
	}
	if _, ok := _c.mutation.InviteeID(); !ok {
		return &ValidationError{Name: "invitee_id", err: errors.New(`ent: missing required field "ReferralCommission.invitee_id"`)}
	}
	if _, ok := _c.mutation.OrderID(); !ok {
		return &ValidationError{Name: "order_id", err: errors.New(`ent: missing required field "ReferralCommission.order_id"`)}
	}
	if _, ok := _c.mutation.OrderAmountUsd(); !ok {
		return &ValidationError{Name: "order_amount_usd", err: errors.New(`ent: missing required field "ReferralCommission.order_amount_usd"`)}
	}
	if _, ok := _c.mutation.CommissionRate(); !ok {
		return &ValidationError{Name: "commission_rate", err: errors.New(`ent: missing required field "ReferralCommission.commission_rate"`)}
	}
	if _, ok := _c.mutation.CommissionAmount(); !ok {
		return &ValidationError{Name: "commission_amount", err: errors.New(`ent: missing required field "ReferralCommission.commission_amount"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "ReferralCommission.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := referralcommission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ReferralCommission.created_at"`)}
	}
	return nil
}

func (_c *ReferralCommissionCreate) sqlSave(ctx context.Context) (*ReferralCommission, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferralCommissionCreate) createSpec() (*ReferralCommission, *sqlgraph.CreateSpec) {
	var (
		_node = &ReferralCommission{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referralcommission.Table, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.InviterID(); ok {
		_spec.SetField(referralcommission.FieldInviterID, field.TypeInt64, value)
		_node.InviterID = value
	}
	if value, ok := _c.mutation.InviteeID(); ok {
		_spec.SetField(referralcommission.FieldInviteeID, field.TypeInt64, value)
		_node.InviteeID = value
	}
	if value, ok := _c.mutation.OrderID(); ok {
		_spec.SetField(referralcommission.FieldOrderID, field.TypeInt64, value)
		_node.OrderID = value
	}
	if value, ok := _c.mutation.OrderAmountUsd(); ok {
		_spec.SetField(referralcommission.FieldOrderAmountUsd, field.TypeFloat64, value)
		_node.OrderAmountUsd = value
	}
	if value, ok := _c.mutation.CommissionRate(); ok {
		_spec.SetField(referralcommission.FieldCommissionRate, field.TypeFloat64, value)
		_node.CommissionRate = value
	}
	if value, ok := _c.mutation.CommissionAmount(); ok {
		_spec.SetField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
		_node.CommissionAmount = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(referralcommission.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SettledAt(); ok {
		_spec.SetField(referralcommission.FieldSettledAt, field.TypeTime, value)
		_node.SettledAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(referralcommission.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralCommission.Create().
//		SetInviterID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralCommissionUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCommissionCreate) OnConflict(opts ...sql.ConflictOption) *ReferralCommissionUpsertOne {
	_c.conflict = opts
	return &ReferralCommissionUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCommissionCreate) OnConflictColumns(columns ...string) *ReferralCommissionUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralCommissionUpsertOne{
		create: _c,
	}
}

type (
	// ReferralCommissionUpsertOne is the builder for "upsert"-ing
	//  one ReferralCommission node.
	ReferralCommissionUpsertOne struct {
		create *ReferralCommissionCreate
	}

	// ReferralCommissionUpsert is the "OnConflict" setter.
	ReferralCommissionUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviterID sets the "inviter_id" field.
func (u *ReferralCommissionUpsert) SetInviterID(v int64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldInviterID, v)
	return u
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateInviterID() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldInviterID)
	return u
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralCommissionUpsert) AddInviterID(v int64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldInviterID, v)
	return u
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralCommissionUpsert) SetInviteeID(v int64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldInviteeID, v)
	return u
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateInviteeID() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldInviteeID)
	return u
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralCommissionUpsert) AddInviteeID(v int64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldInviteeID, v)
	return u
}

// SetOrderID sets the "order_id" field.
func (u *ReferralCommissionUpsert) SetOrderID(v int64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldOrderID, v)
	return u
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateOrderID() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldOrderID)
	return u
}

// AddOrderID adds v to the "order_id" field.
func (u *ReferralCommissionUpsert) AddOrderID(v int64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldOrderID, v)
	return u
}

// SetOrderAmountUsd sets the "order_amount_usd" field.
func (u *ReferralCommissionUpsert) SetOrderAmountUsd(v float64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldOrderAmountUsd, v)
	return u
}

// UpdateOrderAmountUsd sets the "order_amount_usd" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateOrderAmountUsd() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldOrderAmountUsd)
	return u
}

// AddOrderAmountUsd adds v to the "order_amount_usd" field.
func (u *ReferralCommissionUpsert) AddOrderAmountUsd(v float64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldOrderAmountUsd, v)
	return u
}

// SetCommissionRate sets the "commission_rate" field.
func (u *ReferralCommissionUpsert) SetCommissionRate(v float64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldCommissionRate, v)
	return u
}

// UpdateCommissionRate sets the "commission_rate" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateCommissionRate() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldCommissionRate)
	return u
}

// AddCommissionRate adds v to the "commission_rate" field.
func (u *ReferralCommissionUpsert) AddCommissionRate(v float64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldCommissionRate, v)
	return u
}

// SetCommissionAmount sets the "commission_amount" field.
func (u *ReferralCommissionUpsert) SetCommissionAmount(v float64) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldCommissionAmount, v)
	return u
}

// UpdateCommissionAmount sets the "commission_amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateCommissionAmount() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldCommissionAmount)
	return u
}

// AddCommissionAmount adds v to the "commission_amount" field.
func (u *ReferralCommissionUpsert) AddCommissionAmount(v float64) *ReferralCommissionUpsert {
	u.Add(referralcommission.FieldCommissionAmount, v)
	return u
}

// SetStatus sets the "status" field.
func (u *ReferralCommissionUpsert) SetStatus(v string) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateStatus() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldStatus)
	return u
}

// SetSettledAt sets the "settled_at" field.
func (u *ReferralCommissionUpsert) SetSettledAt(v time.Time) *ReferralCommissionUpsert {
	u.Set(referralcommission.FieldSettledAt, v)
	return u
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *ReferralCommissionUpsert) UpdateSettledAt() *ReferralCommissionUpsert {
	u.SetExcluded(referralcommission.FieldSettledAt)
	return u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *ReferralCommissionUpsert) ClearSettledAt() *ReferralCommissionUpsert {
	u.SetNull(referralcommission.FieldSettledAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralCommissionUpsertOne) UpdateNewValues() *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(referralcommission.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReferralCommissionUpsertOne) Ignore() *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralCommissionUpsertOne) DoNothing() *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCommissionCreate.OnConflict
// documentation for more info.
func (u *ReferralCommissionUpsertOne) Update(set func(*ReferralCommissionUpsert)) *ReferralCommissionUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralCommissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *ReferralCommissionUpsertOne) SetInviterID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetInviterID(v)
	})
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralCommissionUpsertOne) AddInviterID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateInviterID() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralCommissionUpsertOne) SetInviteeID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetInviteeID(v)
	})
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralCommissionUpsertOne) AddInviteeID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateInviteeID() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateInviteeID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *ReferralCommissionUpsertOne) SetOrderID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *ReferralCommissionUpsertOne) AddOrderID(v int64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateOrderID() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateOrderID()
	})
}

// SetOrderAmountUsd sets the "order_amount_usd" field.
func (u *ReferralCommissionUpsertOne) SetOrderAmountUsd(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetOrderAmountUsd(v)
	})
}

// AddOrderAmountUsd adds v to the "order_amount_usd" field.
func (u *ReferralCommissionUpsertOne) AddOrderAmountUsd(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddOrderAmountUsd(v)
	})
}

// UpdateOrderAmountUsd sets the "order_amount_usd" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateOrderAmountUsd() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateOrderAmountUsd()
	})
}

// SetCommissionRate sets the "commission_rate" field.
func (u *ReferralCommissionUpsertOne) SetCommissionRate(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetCommissionRate(v)
	})
}

// AddCommissionRate adds v to the "commission_rate" field.
func (u *ReferralCommissionUpsertOne) AddCommissionRate(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddCommissionRate(v)
	})
}

// UpdateCommissionRate sets the "commission_rate" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateCommissionRate() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateCommissionRate()
	})
}

// SetCommissionAmount sets the "commission_amount" field.
func (u *ReferralCommissionUpsertOne) SetCommissionAmount(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetCommissionAmount(v)
	})
}

// AddCommissionAmount adds v to the "commission_amount" field.
func (u *ReferralCommissionUpsertOne) AddCommissionAmount(v float64) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddCommissionAmount(v)
	})
}

// UpdateCommissionAmount sets the "commission_amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateCommissionAmount() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateCommissionAmount()
	})
}

// SetStatus sets the "status" field.
func (u *ReferralCommissionUpsertOne) SetStatus(v string) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateStatus() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateStatus()
	})
}

// SetSettledAt sets the "settled_at" field.
func (u *ReferralCommissionUpsertOne) SetSettledAt(v time.Time) *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetSettledAt(v)
	})
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *ReferralCommissionUpsertOne) UpdateSettledAt() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateSettledAt()
	})
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *ReferralCommissionUpsertOne) ClearSettledAt() *ReferralCommissionUpsertOne {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.ClearSettledAt()
	})
}

// Exec executes the query.
func (u *ReferralCommissionUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCommissionCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralCommissionUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReferralCommissionUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReferralCommissionUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReferralCommissionCreateBulk is the builder for creating many ReferralCommission entities in bulk.
type ReferralCommissionCreateBulk struct {
	config
	err      error
	builders []*ReferralCommissionCreate
	conflict []sql.ConflictOption
}

// Save creates the ReferralCommission entities in the database.
func (_c *ReferralCommissionCreateBulk) Save(ctx context.Context) ([]*ReferralCommission, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ReferralCommission, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralCommissionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferralCommissionCreateBulk) SaveX(ctx context.Context) []*ReferralCommission {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCommissionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCommissionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.ReferralCommission.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralCommissionUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCommissionCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReferralCommissionUpsertBulk {
	_c.conflict = opts
	return &ReferralCommissionUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCommissionCreateBulk) OnConflictColumns(columns ...string) *ReferralCommissionUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralCommissionUpsertBulk{
		create: _c,
	}
}

// ReferralCommissionUpsertBulk is the builder for "upsert"-ing
// a bulk of ReferralCommission nodes.
type ReferralCommissionUpsertBulk struct {
	create *ReferralCommissionCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralCommissionUpsertBulk) UpdateNewValues() *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(referralcommission.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.ReferralCommission.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReferralCommissionUpsertBulk) Ignore() *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralCommissionUpsertBulk) DoNothing() *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCommissionCreateBulk.OnConflict
// documentation for more info.
func (u *ReferralCommissionUpsertBulk) Update(set func(*ReferralCommissionUpsert)) *ReferralCommissionUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralCommissionUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *ReferralCommissionUpsertBulk) SetInviterID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetInviterID(v)
	})
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralCommissionUpsertBulk) AddInviterID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateInviterID() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralCommissionUpsertBulk) SetInviteeID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetInviteeID(v)
	})
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralCommissionUpsertBulk) AddInviteeID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateInviteeID() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateInviteeID()
	})
}

// SetOrderID sets the "order_id" field.
func (u *ReferralCommissionUpsertBulk) SetOrderID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetOrderID(v)
	})
}

// AddOrderID adds v to the "order_id" field.
func (u *ReferralCommissionUpsertBulk) AddOrderID(v int64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddOrderID(v)
	})
}

// UpdateOrderID sets the "order_id" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateOrderID() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateOrderID()
	})
}

// SetOrderAmountUsd sets the "order_amount_usd" field.
func (u *ReferralCommissionUpsertBulk) SetOrderAmountUsd(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetOrderAmountUsd(v)
	})
}

// AddOrderAmountUsd adds v to the "order_amount_usd" field.
func (u *ReferralCommissionUpsertBulk) AddOrderAmountUsd(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddOrderAmountUsd(v)
	})
}

// UpdateOrderAmountUsd sets the "order_amount_usd" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateOrderAmountUsd() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateOrderAmountUsd()
	})
}

// SetCommissionRate sets the "commission_rate" field.
func (u *ReferralCommissionUpsertBulk) SetCommissionRate(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetCommissionRate(v)
	})
}

// AddCommissionRate adds v to the "commission_rate" field.
func (u *ReferralCommissionUpsertBulk) AddCommissionRate(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddCommissionRate(v)
	})
}

// UpdateCommissionRate sets the "commission_rate" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateCommissionRate() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateCommissionRate()
	})
}

// SetCommissionAmount sets the "commission_amount" field.
func (u *ReferralCommissionUpsertBulk) SetCommissionAmount(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetCommissionAmount(v)
	})
}

// AddCommissionAmount adds v to the "commission_amount" field.
func (u *ReferralCommissionUpsertBulk) AddCommissionAmount(v float64) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.AddCommissionAmount(v)
	})
}

// UpdateCommissionAmount sets the "commission_amount" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateCommissionAmount() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateCommissionAmount()
	})
}

// SetStatus sets the "status" field.
func (u *ReferralCommissionUpsertBulk) SetStatus(v string) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateStatus() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateStatus()
	})
}

// SetSettledAt sets the "settled_at" field.
func (u *ReferralCommissionUpsertBulk) SetSettledAt(v time.Time) *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.SetSettledAt(v)
	})
}

// UpdateSettledAt sets the "settled_at" field to the value that was provided on create.
func (u *ReferralCommissionUpsertBulk) UpdateSettledAt() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.UpdateSettledAt()
	})
}

// ClearSettledAt clears the value of the "settled_at" field.
func (u *ReferralCommissionUpsertBulk) ClearSettledAt() *ReferralCommissionUpsertBulk {
	return u.Update(func(s *ReferralCommissionUpsert) {
		s.ClearSettledAt()
	})
}

// Exec executes the query.
func (u *ReferralCommissionUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReferralCommissionCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCommissionCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralCommissionUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
