// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
)

// ReferralCommission is the model entity for the ReferralCommission schema.
type ReferralCommission struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// InviterID holds the value of the "inviter_id" field.
	InviterID int64 `json:"inviter_id,omitempty"`
	// InviteeID holds the value of the "invitee_id" field.
	InviteeID int64 `json:"invitee_id,omitempty"`
	// OrderID holds the value of the "order_id" field.
	OrderID int64 `json:"order_id,omitempty"`
	// OrderAmountUsd holds the value of the "order_amount_usd" field.
	OrderAmountUsd float64 `json:"order_amount_usd,omitempty"`
	// CommissionRate holds the value of the "commission_rate" field.
	CommissionRate float64 `json:"commission_rate,omitempty"`
	// CommissionAmount holds the value of the "commission_amount" field.
	CommissionAmount float64 `json:"commission_amount,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SettledAt holds the value of the "settled_at" field.
	SettledAt *time.Time `json:"settled_at,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt    time.Time `json:"created_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ReferralCommission) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case referralcommission.FieldOrderAmountUsd, referralcommission.FieldCommissionRate, referralcommission.FieldCommissionAmount:
			values[i] = new(sql.NullFloat64)
		case referralcommission.FieldID, referralcommission.FieldInviterID, referralcommission.FieldInviteeID, referralcommission.FieldOrderID:
			values[i] = new(sql.NullInt64)
		case referralcommission.FieldStatus:
			values[i] = new(sql.NullString)
		case referralcommission.FieldSettledAt, referralcommission.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ReferralCommission fields.
func (_m *ReferralCommission) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case referralcommission.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case referralcommission.FieldInviterID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field inviter_id", values[i])
			} else if value.Valid {
				_m.InviterID = value.Int64
			}
		case referralcommission.FieldInviteeID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field invitee_id", values[i])
			} else if value.Valid {
				_m.InviteeID = value.Int64
			}
		case referralcommission.FieldOrderID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field order_id", values[i])
			} else if value.Valid {
				_m.OrderID = value.Int64
			}
		case referralcommission.FieldOrderAmountUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field order_amount_usd", values[i])
			} else if value.Valid {
				_m.OrderAmountUsd = value.Float64
			}
		case referralcommission.FieldCommissionRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field commission_rate", values[i])
			} else if value.Valid {
				_m.CommissionRate = value.Float64
			}
		case referralcommission.FieldCommissionAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field commission_amount", values[i])
			} else if value.Valid {
				_m.CommissionAmount = value.Float64
			}
		case referralcommission.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case referralcommission.FieldSettledAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field settled_at", values[i])
			} else if value.Valid {
				_m.SettledAt = new(time.Time)
				*_m.SettledAt = value.Time
			}
		case referralcommission.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ReferralCommission.
// This includes values selected through modifiers, order, etc.
func (_m *ReferralCommission) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ReferralCommission.
// Note that you need to call ReferralCommission.Unwrap() before calling this method if this ReferralCommission
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ReferralCommission) Update() *ReferralCommissionUpdateOne {
	return NewReferralCommissionClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ReferralCommission entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ReferralCommission) Unwrap() *ReferralCommission {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ReferralCommission is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ReferralCommission) String() string {
	var builder strings.Builder
	builder.WriteString("ReferralCommission(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("inviter_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviterID))
	builder.WriteString(", ")
	builder.WriteString("invitee_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.InviteeID))
	builder.WriteString(", ")
	builder.WriteString("order_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderID))
	builder.WriteString(", ")
	builder.WriteString("order_amount_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.OrderAmountUsd))
	builder.WriteString(", ")
	builder.WriteString("commission_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommissionRate))
	builder.WriteString(", ")
	builder.WriteString("commission_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.CommissionAmount))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	if v := _m.SettledAt; v != nil {
		builder.WriteString("settled_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ReferralCommissions is a parsable slice of ReferralCommission.
type ReferralCommissions []*ReferralCommission
