// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/referral"
)

// ReferralCreate is the builder for creating a Referral entity.
type ReferralCreate struct {
	config
	mutation *ReferralMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetInviterID sets the "inviter_id" field.
func (_c *ReferralCreate) SetInviterID(v int64) *ReferralCreate {
	_c.mutation.SetInviterID(v)
	return _c
}

// SetInviteeID sets the "invitee_id" field.
func (_c *ReferralCreate) SetInviteeID(v int64) *ReferralCreate {
	_c.mutation.SetInviteeID(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ReferralCreate) SetCreatedAt(v time.Time) *ReferralCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ReferralCreate) SetNillableCreatedAt(v *time.Time) *ReferralCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// Mutation returns the ReferralMutation object of the builder.
func (_c *ReferralCreate) Mutation() *ReferralMutation {
	return _c.mutation
}

// Save creates the Referral in the database.
func (_c *ReferralCreate) Save(ctx context.Context) (*Referral, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ReferralCreate) SaveX(ctx context.Context) *Referral {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ReferralCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := referral.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ReferralCreate) check() error {
	if _, ok := _c.mutation.InviterID(); !ok {
		return &ValidationError{Name: "inviter_id", err: errors.New(`ent: missing required field "Referral.inviter_id"`)}
	}
	if _, ok := _c.mutation.InviteeID(); !ok {
		return &ValidationError{Name: "invitee_id", err: errors.New(`ent: missing required field "Referral.invitee_id"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "Referral.created_at"`)}
	}
	return nil
}

func (_c *ReferralCreate) sqlSave(ctx context.Context) (*Referral, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ReferralCreate) createSpec() (*Referral, *sqlgraph.CreateSpec) {
	var (
		_node = &Referral{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(referral.Table, sqlgraph.NewFieldSpec(referral.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.InviterID(); ok {
		_spec.SetField(referral.FieldInviterID, field.TypeInt64, value)
		_node.InviterID = value
	}
	if value, ok := _c.mutation.InviteeID(); ok {
		_spec.SetField(referral.FieldInviteeID, field.TypeInt64, value)
		_node.InviteeID = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(referral.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Referral.Create().
//		SetInviterID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCreate) OnConflict(opts ...sql.ConflictOption) *ReferralUpsertOne {
	_c.conflict = opts
	return &ReferralUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Referral.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCreate) OnConflictColumns(columns ...string) *ReferralUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralUpsertOne{
		create: _c,
	}
}

type (
	// ReferralUpsertOne is the builder for "upsert"-ing
	//  one Referral node.
	ReferralUpsertOne struct {
		create *ReferralCreate
	}

	// ReferralUpsert is the "OnConflict" setter.
	ReferralUpsert struct {
		*sql.UpdateSet
	}
)

// SetInviterID sets the "inviter_id" field.
func (u *ReferralUpsert) SetInviterID(v int64) *ReferralUpsert {
	u.Set(referral.FieldInviterID, v)
	return u
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralUpsert) UpdateInviterID() *ReferralUpsert {
	u.SetExcluded(referral.FieldInviterID)
	return u
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralUpsert) AddInviterID(v int64) *ReferralUpsert {
	u.Add(referral.FieldInviterID, v)
	return u
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralUpsert) SetInviteeID(v int64) *ReferralUpsert {
	u.Set(referral.FieldInviteeID, v)
	return u
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralUpsert) UpdateInviteeID() *ReferralUpsert {
	u.SetExcluded(referral.FieldInviteeID)
	return u
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralUpsert) AddInviteeID(v int64) *ReferralUpsert {
	u.Add(referral.FieldInviteeID, v)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.Referral.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralUpsertOne) UpdateNewValues() *ReferralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(referral.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Referral.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *ReferralUpsertOne) Ignore() *ReferralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralUpsertOne) DoNothing() *ReferralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCreate.OnConflict
// documentation for more info.
func (u *ReferralUpsertOne) Update(set func(*ReferralUpsert)) *ReferralUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *ReferralUpsertOne) SetInviterID(v int64) *ReferralUpsertOne {
	return u.Update(func(s *ReferralUpsert) {
		s.SetInviterID(v)
	})
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralUpsertOne) AddInviterID(v int64) *ReferralUpsertOne {
	return u.Update(func(s *ReferralUpsert) {
		s.AddInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralUpsertOne) UpdateInviterID() *ReferralUpsertOne {
	return u.Update(func(s *ReferralUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralUpsertOne) SetInviteeID(v int64) *ReferralUpsertOne {
	return u.Update(func(s *ReferralUpsert) {
		s.SetInviteeID(v)
	})
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralUpsertOne) AddInviteeID(v int64) *ReferralUpsertOne {
	return u.Update(func(s *ReferralUpsert) {
		s.AddInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralUpsertOne) UpdateInviteeID() *ReferralUpsertOne {
	return u.Update(func(s *ReferralUpsert) {
		s.UpdateInviteeID()
	})
}

// Exec executes the query.
func (u *ReferralUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *ReferralUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *ReferralUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// ReferralCreateBulk is the builder for creating many Referral entities in bulk.
type ReferralCreateBulk struct {
	config
	err      error
	builders []*ReferralCreate
	conflict []sql.ConflictOption
}

// Save creates the Referral entities in the database.
func (_c *ReferralCreateBulk) Save(ctx context.Context) ([]*Referral, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*Referral, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ReferralMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ReferralCreateBulk) SaveX(ctx context.Context) []*Referral {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ReferralCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ReferralCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.Referral.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.ReferralUpsert) {
//			SetInviterID(v+v).
//		}).
//		Exec(ctx)
func (_c *ReferralCreateBulk) OnConflict(opts ...sql.ConflictOption) *ReferralUpsertBulk {
	_c.conflict = opts
	return &ReferralUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.Referral.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *ReferralCreateBulk) OnConflictColumns(columns ...string) *ReferralUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &ReferralUpsertBulk{
		create: _c,
	}
}

// ReferralUpsertBulk is the builder for "upsert"-ing
// a bulk of Referral nodes.
type ReferralUpsertBulk struct {
	create *ReferralCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.Referral.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *ReferralUpsertBulk) UpdateNewValues() *ReferralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(referral.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.Referral.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *ReferralUpsertBulk) Ignore() *ReferralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *ReferralUpsertBulk) DoNothing() *ReferralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the ReferralCreateBulk.OnConflict
// documentation for more info.
func (u *ReferralUpsertBulk) Update(set func(*ReferralUpsert)) *ReferralUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&ReferralUpsert{UpdateSet: update})
	}))
	return u
}

// SetInviterID sets the "inviter_id" field.
func (u *ReferralUpsertBulk) SetInviterID(v int64) *ReferralUpsertBulk {
	return u.Update(func(s *ReferralUpsert) {
		s.SetInviterID(v)
	})
}

// AddInviterID adds v to the "inviter_id" field.
func (u *ReferralUpsertBulk) AddInviterID(v int64) *ReferralUpsertBulk {
	return u.Update(func(s *ReferralUpsert) {
		s.AddInviterID(v)
	})
}

// UpdateInviterID sets the "inviter_id" field to the value that was provided on create.
func (u *ReferralUpsertBulk) UpdateInviterID() *ReferralUpsertBulk {
	return u.Update(func(s *ReferralUpsert) {
		s.UpdateInviterID()
	})
}

// SetInviteeID sets the "invitee_id" field.
func (u *ReferralUpsertBulk) SetInviteeID(v int64) *ReferralUpsertBulk {
	return u.Update(func(s *ReferralUpsert) {
		s.SetInviteeID(v)
	})
}

// AddInviteeID adds v to the "invitee_id" field.
func (u *ReferralUpsertBulk) AddInviteeID(v int64) *ReferralUpsertBulk {
	return u.Update(func(s *ReferralUpsert) {
		s.AddInviteeID(v)
	})
}

// UpdateInviteeID sets the "invitee_id" field to the value that was provided on create.
func (u *ReferralUpsertBulk) UpdateInviteeID() *ReferralUpsertBulk {
	return u.Update(func(s *ReferralUpsert) {
		s.UpdateInviteeID()
	})
}

// Exec executes the query.
func (u *ReferralUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the ReferralCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for ReferralCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *ReferralUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
