// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/referralcommission"
)

// ReferralCommissionUpdate is the builder for updating ReferralCommission entities.
type ReferralCommissionUpdate struct {
	config
	hooks    []Hook
	mutation *ReferralCommissionMutation
}

// Where appends a list predicates to the ReferralCommissionUpdate builder.
func (_u *ReferralCommissionUpdate) Where(ps ...predicate.ReferralCommission) *ReferralCommissionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetInviterID sets the "inviter_id" field.
func (_u *ReferralCommissionUpdate) SetInviterID(v int64) *ReferralCommissionUpdate {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableInviterID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *ReferralCommissionUpdate) AddInviterID(v int64) *ReferralCommissionUpdate {
	_u.mutation.AddInviterID(v)
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *ReferralCommissionUpdate) SetInviteeID(v int64) *ReferralCommissionUpdate {
	_u.mutation.ResetInviteeID()
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableInviteeID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// AddInviteeID adds value to the "invitee_id" field.
func (_u *ReferralCommissionUpdate) AddInviteeID(v int64) *ReferralCommissionUpdate {
	_u.mutation.AddInviteeID(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *ReferralCommissionUpdate) SetOrderID(v int64) *ReferralCommissionUpdate {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableOrderID(v *int64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *ReferralCommissionUpdate) AddOrderID(v int64) *ReferralCommissionUpdate {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetOrderAmountUsd sets the "order_amount_usd" field.
func (_u *ReferralCommissionUpdate) SetOrderAmountUsd(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetOrderAmountUsd()
	_u.mutation.SetOrderAmountUsd(v)
	return _u
}

// SetNillableOrderAmountUsd sets the "order_amount_usd" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableOrderAmountUsd(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetOrderAmountUsd(*v)
	}
	return _u
}

// AddOrderAmountUsd adds value to the "order_amount_usd" field.
func (_u *ReferralCommissionUpdate) AddOrderAmountUsd(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddOrderAmountUsd(v)
	return _u
}

// SetCommissionRate sets the "commission_rate" field.
func (_u *ReferralCommissionUpdate) SetCommissionRate(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetCommissionRate()
	_u.mutation.SetCommissionRate(v)
	return _u
}

// SetNillableCommissionRate sets the "commission_rate" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableCommissionRate(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetCommissionRate(*v)
	}
	return _u
}

// AddCommissionRate adds value to the "commission_rate" field.
func (_u *ReferralCommissionUpdate) AddCommissionRate(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddCommissionRate(v)
	return _u
}

// SetCommissionAmount sets the "commission_amount" field.
func (_u *ReferralCommissionUpdate) SetCommissionAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.ResetCommissionAmount()
	_u.mutation.SetCommissionAmount(v)
	return _u
}

// SetNillableCommissionAmount sets the "commission_amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableCommissionAmount(v *float64) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetCommissionAmount(*v)
	}
	return _u
}

// AddCommissionAmount adds value to the "commission_amount" field.
func (_u *ReferralCommissionUpdate) AddCommissionAmount(v float64) *ReferralCommissionUpdate {
	_u.mutation.AddCommissionAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralCommissionUpdate) SetStatus(v string) *ReferralCommissionUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableStatus(v *string) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *ReferralCommissionUpdate) SetSettledAt(v time.Time) *ReferralCommissionUpdate {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *ReferralCommissionUpdate) SetNillableSettledAt(v *time.Time) *ReferralCommissionUpdate {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *ReferralCommissionUpdate) ClearSettledAt() *ReferralCommissionUpdate {
	_u.mutation.ClearSettledAt()
	return _u
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_u *ReferralCommissionUpdate) Mutation() *ReferralCommissionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReferralCommissionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReferralCommissionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralCommissionUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := referralcommission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReferralCommissionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(referralcommission.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(referralcommission.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InviteeID(); ok {
		_spec.SetField(referralcommission.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviteeID(); ok {
		_spec.AddField(referralcommission.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(referralcommission.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(referralcommission.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderAmountUsd(); ok {
		_spec.SetField(referralcommission.FieldOrderAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOrderAmountUsd(); ok {
		_spec.AddField(referralcommission.FieldOrderAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionRate(); ok {
		_spec.SetField(referralcommission.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRate(); ok {
		_spec.AddField(referralcommission.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionAmount(); ok {
		_spec.SetField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionAmount(); ok {
		_spec.AddField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralcommission.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(referralcommission.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(referralcommission.FieldSettledAt, field.TypeTime)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReferralCommissionUpdateOne is the builder for updating a single ReferralCommission entity.
type ReferralCommissionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReferralCommissionMutation
}

// SetInviterID sets the "inviter_id" field.
func (_u *ReferralCommissionUpdateOne) SetInviterID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetInviterID()
	_u.mutation.SetInviterID(v)
	return _u
}

// SetNillableInviterID sets the "inviter_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableInviterID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetInviterID(*v)
	}
	return _u
}

// AddInviterID adds value to the "inviter_id" field.
func (_u *ReferralCommissionUpdateOne) AddInviterID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.AddInviterID(v)
	return _u
}

// SetInviteeID sets the "invitee_id" field.
func (_u *ReferralCommissionUpdateOne) SetInviteeID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetInviteeID()
	_u.mutation.SetInviteeID(v)
	return _u
}

// SetNillableInviteeID sets the "invitee_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableInviteeID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetInviteeID(*v)
	}
	return _u
}

// AddInviteeID adds value to the "invitee_id" field.
func (_u *ReferralCommissionUpdateOne) AddInviteeID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.AddInviteeID(v)
	return _u
}

// SetOrderID sets the "order_id" field.
func (_u *ReferralCommissionUpdateOne) SetOrderID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetOrderID()
	_u.mutation.SetOrderID(v)
	return _u
}

// SetNillableOrderID sets the "order_id" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableOrderID(v *int64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetOrderID(*v)
	}
	return _u
}

// AddOrderID adds value to the "order_id" field.
func (_u *ReferralCommissionUpdateOne) AddOrderID(v int64) *ReferralCommissionUpdateOne {
	_u.mutation.AddOrderID(v)
	return _u
}

// SetOrderAmountUsd sets the "order_amount_usd" field.
func (_u *ReferralCommissionUpdateOne) SetOrderAmountUsd(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetOrderAmountUsd()
	_u.mutation.SetOrderAmountUsd(v)
	return _u
}

// SetNillableOrderAmountUsd sets the "order_amount_usd" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableOrderAmountUsd(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetOrderAmountUsd(*v)
	}
	return _u
}

// AddOrderAmountUsd adds value to the "order_amount_usd" field.
func (_u *ReferralCommissionUpdateOne) AddOrderAmountUsd(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddOrderAmountUsd(v)
	return _u
}

// SetCommissionRate sets the "commission_rate" field.
func (_u *ReferralCommissionUpdateOne) SetCommissionRate(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetCommissionRate()
	_u.mutation.SetCommissionRate(v)
	return _u
}

// SetNillableCommissionRate sets the "commission_rate" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableCommissionRate(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetCommissionRate(*v)
	}
	return _u
}

// AddCommissionRate adds value to the "commission_rate" field.
func (_u *ReferralCommissionUpdateOne) AddCommissionRate(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddCommissionRate(v)
	return _u
}

// SetCommissionAmount sets the "commission_amount" field.
func (_u *ReferralCommissionUpdateOne) SetCommissionAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.ResetCommissionAmount()
	_u.mutation.SetCommissionAmount(v)
	return _u
}

// SetNillableCommissionAmount sets the "commission_amount" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableCommissionAmount(v *float64) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetCommissionAmount(*v)
	}
	return _u
}

// AddCommissionAmount adds value to the "commission_amount" field.
func (_u *ReferralCommissionUpdateOne) AddCommissionAmount(v float64) *ReferralCommissionUpdateOne {
	_u.mutation.AddCommissionAmount(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *ReferralCommissionUpdateOne) SetStatus(v string) *ReferralCommissionUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableStatus(v *string) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSettledAt sets the "settled_at" field.
func (_u *ReferralCommissionUpdateOne) SetSettledAt(v time.Time) *ReferralCommissionUpdateOne {
	_u.mutation.SetSettledAt(v)
	return _u
}

// SetNillableSettledAt sets the "settled_at" field if the given value is not nil.
func (_u *ReferralCommissionUpdateOne) SetNillableSettledAt(v *time.Time) *ReferralCommissionUpdateOne {
	if v != nil {
		_u.SetSettledAt(*v)
	}
	return _u
}

// ClearSettledAt clears the value of the "settled_at" field.
func (_u *ReferralCommissionUpdateOne) ClearSettledAt() *ReferralCommissionUpdateOne {
	_u.mutation.ClearSettledAt()
	return _u
}

// Mutation returns the ReferralCommissionMutation object of the builder.
func (_u *ReferralCommissionUpdateOne) Mutation() *ReferralCommissionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ReferralCommissionUpdate builder.
func (_u *ReferralCommissionUpdateOne) Where(ps ...predicate.ReferralCommission) *ReferralCommissionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReferralCommissionUpdateOne) Select(field string, fields ...string) *ReferralCommissionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ReferralCommission entity.
func (_u *ReferralCommissionUpdateOne) Save(ctx context.Context) (*ReferralCommission, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReferralCommissionUpdateOne) SaveX(ctx context.Context) *ReferralCommission {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReferralCommissionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReferralCommissionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReferralCommissionUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := referralcommission.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "ReferralCommission.status": %w`, err)}
		}
	}
	return nil
}

func (_u *ReferralCommissionUpdateOne) sqlSave(ctx context.Context) (_node *ReferralCommission, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(referralcommission.Table, referralcommission.Columns, sqlgraph.NewFieldSpec(referralcommission.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ReferralCommission.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, referralcommission.FieldID)
		for _, f := range fields {
			if !referralcommission.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != referralcommission.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.InviterID(); ok {
		_spec.SetField(referralcommission.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviterID(); ok {
		_spec.AddField(referralcommission.FieldInviterID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.InviteeID(); ok {
		_spec.SetField(referralcommission.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedInviteeID(); ok {
		_spec.AddField(referralcommission.FieldInviteeID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderID(); ok {
		_spec.SetField(referralcommission.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedOrderID(); ok {
		_spec.AddField(referralcommission.FieldOrderID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.OrderAmountUsd(); ok {
		_spec.SetField(referralcommission.FieldOrderAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedOrderAmountUsd(); ok {
		_spec.AddField(referralcommission.FieldOrderAmountUsd, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionRate(); ok {
		_spec.SetField(referralcommission.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionRate(); ok {
		_spec.AddField(referralcommission.FieldCommissionRate, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.CommissionAmount(); ok {
		_spec.SetField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedCommissionAmount(); ok {
		_spec.AddField(referralcommission.FieldCommissionAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(referralcommission.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.SettledAt(); ok {
		_spec.SetField(referralcommission.FieldSettledAt, field.TypeTime, value)
	}
	if _u.mutation.SettledAtCleared() {
		_spec.ClearField(referralcommission.FieldSettledAt, field.TypeTime)
	}
	_node = &ReferralCommission{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{referralcommission.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
