// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/vendor"
)

// Vendor is the model entity for the Vendor schema.
type Vendor struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// official | reseller
	VendorType string `json:"vendor_type,omitempty"`
	// claude | openai | gemini (仅 vendor_type=official)
	OfficialPlatform *string `json:"official_platform,omitempty"`
	// sub2api | newapi | other (仅 vendor_type=reseller)
	ResellerPlatform *string `json:"reseller_platform,omitempty"`
	// 渠道商主 API Key (仅 vendor_type=reseller)
	ResellerAPIKey *string `json:"reseller_api_key,omitempty"`
	// anthropic | openai
	APIFormat string `json:"api_format,omitempty"`
	// 供应商 API 地址
	BaseURL string `json:"base_url,omitempty"`
	// api_key | session | bearer
	AuthType string `json:"auth_type,omitempty"`
	// 自定义 API 路径覆盖
	APIPathOverride *string `json:"api_path_override,omitempty"`
	// 额外请求头
	ExtraHeaders map[string]string `json:"extra_headers,omitempty"`
	// token | quota | subscription
	BillingType string `json:"billing_type,omitempty"`
	// CostPer1kInput holds the value of the "cost_per_1k_input" field.
	CostPer1kInput *float64 `json:"cost_per_1k_input,omitempty"`
	// CostPer1kOutput holds the value of the "cost_per_1k_output" field.
	CostPer1kOutput *float64 `json:"cost_per_1k_output,omitempty"`
	// TotalQuotaUsd holds the value of the "total_quota_usd" field.
	TotalQuotaUsd *float64 `json:"total_quota_usd,omitempty"`
	// UsedQuotaUsd holds the value of the "used_quota_usd" field.
	UsedQuotaUsd float64 `json:"used_quota_usd,omitempty"`
	// BalanceUsd holds the value of the "balance_usd" field.
	BalanceUsd *float64 `json:"balance_usd,omitempty"`
	// ExpiresAt holds the value of the "expires_at" field.
	ExpiresAt *time.Time `json:"expires_at,omitempty"`
	// active | suspended | depleted | error
	Status string `json:"status,omitempty"`
	// HealthCheckEnabled holds the value of the "health_check_enabled" field.
	HealthCheckEnabled bool `json:"health_check_enabled,omitempty"`
	// 健康检查间隔（秒）
	HealthCheckInterval int `json:"health_check_interval,omitempty"`
	// HealthCheckModel holds the value of the "health_check_model" field.
	HealthCheckModel string `json:"health_check_model,omitempty"`
	// LastHealthCheckAt holds the value of the "last_health_check_at" field.
	LastHealthCheckAt *time.Time `json:"last_health_check_at,omitempty"`
	// ok | slow | error | timeout
	LastHealthStatus *string `json:"last_health_status,omitempty"`
	// 最近一次健康检查延迟（ms）
	LastHealthLatency *int `json:"last_health_latency,omitempty"`
	// ErrorMessage holds the value of the "error_message" field.
	ErrorMessage *string `json:"error_message,omitempty"`
	// ConsecutiveFailures holds the value of the "consecutive_failures" field.
	ConsecutiveFailures int `json:"consecutive_failures,omitempty"`
	// AutoPurchaseEnabled holds the value of the "auto_purchase_enabled" field.
	AutoPurchaseEnabled bool `json:"auto_purchase_enabled,omitempty"`
	// AutoPurchaseConfig holds the value of the "auto_purchase_config" field.
	AutoPurchaseConfig map[string]interface{} `json:"auto_purchase_config,omitempty"`
	// BalanceAlertEnabled holds the value of the "balance_alert_enabled" field.
	BalanceAlertEnabled bool `json:"balance_alert_enabled,omitempty"`
	// BalanceAlertThreshold holds the value of the "balance_alert_threshold" field.
	BalanceAlertThreshold *float64 `json:"balance_alert_threshold,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VendorQuery when eager-loading is set.
	Edges        VendorEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VendorEdges holds the relations/edges for other nodes in the graph.
type VendorEdges struct {
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e VendorEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[0] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Vendor) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case vendor.FieldExtraHeaders, vendor.FieldAutoPurchaseConfig:
			values[i] = new([]byte)
		case vendor.FieldHealthCheckEnabled, vendor.FieldAutoPurchaseEnabled, vendor.FieldBalanceAlertEnabled:
			values[i] = new(sql.NullBool)
		case vendor.FieldCostPer1kInput, vendor.FieldCostPer1kOutput, vendor.FieldTotalQuotaUsd, vendor.FieldUsedQuotaUsd, vendor.FieldBalanceUsd, vendor.FieldBalanceAlertThreshold:
			values[i] = new(sql.NullFloat64)
		case vendor.FieldID, vendor.FieldHealthCheckInterval, vendor.FieldLastHealthLatency, vendor.FieldConsecutiveFailures:
			values[i] = new(sql.NullInt64)
		case vendor.FieldName, vendor.FieldDescription, vendor.FieldVendorType, vendor.FieldOfficialPlatform, vendor.FieldResellerPlatform, vendor.FieldResellerAPIKey, vendor.FieldAPIFormat, vendor.FieldBaseURL, vendor.FieldAuthType, vendor.FieldAPIPathOverride, vendor.FieldBillingType, vendor.FieldStatus, vendor.FieldHealthCheckModel, vendor.FieldLastHealthStatus, vendor.FieldErrorMessage:
			values[i] = new(sql.NullString)
		case vendor.FieldCreatedAt, vendor.FieldUpdatedAt, vendor.FieldDeletedAt, vendor.FieldExpiresAt, vendor.FieldLastHealthCheckAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Vendor fields.
func (_m *Vendor) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case vendor.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case vendor.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case vendor.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case vendor.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case vendor.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case vendor.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case vendor.FieldVendorType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field vendor_type", values[i])
			} else if value.Valid {
				_m.VendorType = value.String
			}
		case vendor.FieldOfficialPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field official_platform", values[i])
			} else if value.Valid {
				_m.OfficialPlatform = new(string)
				*_m.OfficialPlatform = value.String
			}
		case vendor.FieldResellerPlatform:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reseller_platform", values[i])
			} else if value.Valid {
				_m.ResellerPlatform = new(string)
				*_m.ResellerPlatform = value.String
			}
		case vendor.FieldResellerAPIKey:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reseller_api_key", values[i])
			} else if value.Valid {
				_m.ResellerAPIKey = new(string)
				*_m.ResellerAPIKey = value.String
			}
		case vendor.FieldAPIFormat:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_format", values[i])
			} else if value.Valid {
				_m.APIFormat = value.String
			}
		case vendor.FieldBaseURL:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field base_url", values[i])
			} else if value.Valid {
				_m.BaseURL = value.String
			}
		case vendor.FieldAuthType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field auth_type", values[i])
			} else if value.Valid {
				_m.AuthType = value.String
			}
		case vendor.FieldAPIPathOverride:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field api_path_override", values[i])
			} else if value.Valid {
				_m.APIPathOverride = new(string)
				*_m.APIPathOverride = value.String
			}
		case vendor.FieldExtraHeaders:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field extra_headers", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.ExtraHeaders); err != nil {
					return fmt.Errorf("unmarshal field extra_headers: %w", err)
				}
			}
		case vendor.FieldBillingType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field billing_type", values[i])
			} else if value.Valid {
				_m.BillingType = value.String
			}
		case vendor.FieldCostPer1kInput:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_per_1k_input", values[i])
			} else if value.Valid {
				_m.CostPer1kInput = new(float64)
				*_m.CostPer1kInput = value.Float64
			}
		case vendor.FieldCostPer1kOutput:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field cost_per_1k_output", values[i])
			} else if value.Valid {
				_m.CostPer1kOutput = new(float64)
				*_m.CostPer1kOutput = value.Float64
			}
		case vendor.FieldTotalQuotaUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field total_quota_usd", values[i])
			} else if value.Valid {
				_m.TotalQuotaUsd = new(float64)
				*_m.TotalQuotaUsd = value.Float64
			}
		case vendor.FieldUsedQuotaUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field used_quota_usd", values[i])
			} else if value.Valid {
				_m.UsedQuotaUsd = value.Float64
			}
		case vendor.FieldBalanceUsd:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_usd", values[i])
			} else if value.Valid {
				_m.BalanceUsd = new(float64)
				*_m.BalanceUsd = value.Float64
			}
		case vendor.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = new(time.Time)
				*_m.ExpiresAt = value.Time
			}
		case vendor.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case vendor.FieldHealthCheckEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field health_check_enabled", values[i])
			} else if value.Valid {
				_m.HealthCheckEnabled = value.Bool
			}
		case vendor.FieldHealthCheckInterval:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field health_check_interval", values[i])
			} else if value.Valid {
				_m.HealthCheckInterval = int(value.Int64)
			}
		case vendor.FieldHealthCheckModel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field health_check_model", values[i])
			} else if value.Valid {
				_m.HealthCheckModel = value.String
			}
		case vendor.FieldLastHealthCheckAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field last_health_check_at", values[i])
			} else if value.Valid {
				_m.LastHealthCheckAt = new(time.Time)
				*_m.LastHealthCheckAt = value.Time
			}
		case vendor.FieldLastHealthStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field last_health_status", values[i])
			} else if value.Valid {
				_m.LastHealthStatus = new(string)
				*_m.LastHealthStatus = value.String
			}
		case vendor.FieldLastHealthLatency:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field last_health_latency", values[i])
			} else if value.Valid {
				_m.LastHealthLatency = new(int)
				*_m.LastHealthLatency = int(value.Int64)
			}
		case vendor.FieldErrorMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field error_message", values[i])
			} else if value.Valid {
				_m.ErrorMessage = new(string)
				*_m.ErrorMessage = value.String
			}
		case vendor.FieldConsecutiveFailures:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field consecutive_failures", values[i])
			} else if value.Valid {
				_m.ConsecutiveFailures = int(value.Int64)
			}
		case vendor.FieldAutoPurchaseEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field auto_purchase_enabled", values[i])
			} else if value.Valid {
				_m.AutoPurchaseEnabled = value.Bool
			}
		case vendor.FieldAutoPurchaseConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field auto_purchase_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.AutoPurchaseConfig); err != nil {
					return fmt.Errorf("unmarshal field auto_purchase_config: %w", err)
				}
			}
		case vendor.FieldBalanceAlertEnabled:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field balance_alert_enabled", values[i])
			} else if value.Valid {
				_m.BalanceAlertEnabled = value.Bool
			}
		case vendor.FieldBalanceAlertThreshold:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_alert_threshold", values[i])
			} else if value.Valid {
				_m.BalanceAlertThreshold = new(float64)
				*_m.BalanceAlertThreshold = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Vendor.
// This includes values selected through modifiers, order, etc.
func (_m *Vendor) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryAccounts queries the "accounts" edge of the Vendor entity.
func (_m *Vendor) QueryAccounts() *AccountQuery {
	return NewVendorClient(_m.config).QueryAccounts(_m)
}

// Update returns a builder for updating this Vendor.
// Note that you need to call Vendor.Unwrap() before calling this method if this Vendor
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Vendor) Update() *VendorUpdateOne {
	return NewVendorClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Vendor entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Vendor) Unwrap() *Vendor {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Vendor is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Vendor) String() string {
	var builder strings.Builder
	builder.WriteString("Vendor(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("vendor_type=")
	builder.WriteString(_m.VendorType)
	builder.WriteString(", ")
	if v := _m.OfficialPlatform; v != nil {
		builder.WriteString("official_platform=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResellerPlatform; v != nil {
		builder.WriteString("reseller_platform=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.ResellerAPIKey; v != nil {
		builder.WriteString("reseller_api_key=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("api_format=")
	builder.WriteString(_m.APIFormat)
	builder.WriteString(", ")
	builder.WriteString("base_url=")
	builder.WriteString(_m.BaseURL)
	builder.WriteString(", ")
	builder.WriteString("auth_type=")
	builder.WriteString(_m.AuthType)
	builder.WriteString(", ")
	if v := _m.APIPathOverride; v != nil {
		builder.WriteString("api_path_override=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("extra_headers=")
	builder.WriteString(fmt.Sprintf("%v", _m.ExtraHeaders))
	builder.WriteString(", ")
	builder.WriteString("billing_type=")
	builder.WriteString(_m.BillingType)
	builder.WriteString(", ")
	if v := _m.CostPer1kInput; v != nil {
		builder.WriteString("cost_per_1k_input=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.CostPer1kOutput; v != nil {
		builder.WriteString("cost_per_1k_output=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.TotalQuotaUsd; v != nil {
		builder.WriteString("total_quota_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("used_quota_usd=")
	builder.WriteString(fmt.Sprintf("%v", _m.UsedQuotaUsd))
	builder.WriteString(", ")
	if v := _m.BalanceUsd; v != nil {
		builder.WriteString("balance_usd=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ExpiresAt; v != nil {
		builder.WriteString("expires_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("health_check_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.HealthCheckEnabled))
	builder.WriteString(", ")
	builder.WriteString("health_check_interval=")
	builder.WriteString(fmt.Sprintf("%v", _m.HealthCheckInterval))
	builder.WriteString(", ")
	builder.WriteString("health_check_model=")
	builder.WriteString(_m.HealthCheckModel)
	builder.WriteString(", ")
	if v := _m.LastHealthCheckAt; v != nil {
		builder.WriteString("last_health_check_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.LastHealthStatus; v != nil {
		builder.WriteString("last_health_status=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.LastHealthLatency; v != nil {
		builder.WriteString("last_health_latency=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.ErrorMessage; v != nil {
		builder.WriteString("error_message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("consecutive_failures=")
	builder.WriteString(fmt.Sprintf("%v", _m.ConsecutiveFailures))
	builder.WriteString(", ")
	builder.WriteString("auto_purchase_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoPurchaseEnabled))
	builder.WriteString(", ")
	builder.WriteString("auto_purchase_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.AutoPurchaseConfig))
	builder.WriteString(", ")
	builder.WriteString("balance_alert_enabled=")
	builder.WriteString(fmt.Sprintf("%v", _m.BalanceAlertEnabled))
	builder.WriteString(", ")
	if v := _m.BalanceAlertThreshold; v != nil {
		builder.WriteString("balance_alert_threshold=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// Vendors is a parsable slice of Vendor.
type Vendors []*Vendor
