// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/vpnalertrule"
)

// VpnAlertRuleCreate is the builder for creating a VpnAlertRule entity.
type VpnAlertRuleCreate struct {
	config
	mutation *VpnAlertRuleMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *VpnAlertRuleCreate) SetCreatedAt(v time.Time) *VpnAlertRuleCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VpnAlertRuleCreate) SetNillableCreatedAt(v *time.Time) *VpnAlertRuleCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *VpnAlertRuleCreate) SetUpdatedAt(v time.Time) *VpnAlertRuleCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *VpnAlertRuleCreate) SetNillableUpdatedAt(v *time.Time) *VpnAlertRuleCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetName sets the "name" field.
func (_c *VpnAlertRuleCreate) SetName(v string) *VpnAlertRuleCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetCondition sets the "condition" field.
func (_c *VpnAlertRuleCreate) SetCondition(v string) *VpnAlertRuleCreate {
	_c.mutation.SetCondition(v)
	return _c
}

// SetThreshold sets the "threshold" field.
func (_c *VpnAlertRuleCreate) SetThreshold(v int) *VpnAlertRuleCreate {
	_c.mutation.SetThreshold(v)
	return _c
}

// SetWebhookURL sets the "webhook_url" field.
func (_c *VpnAlertRuleCreate) SetWebhookURL(v string) *VpnAlertRuleCreate {
	_c.mutation.SetWebhookURL(v)
	return _c
}

// SetNillableWebhookURL sets the "webhook_url" field if the given value is not nil.
func (_c *VpnAlertRuleCreate) SetNillableWebhookURL(v *string) *VpnAlertRuleCreate {
	if v != nil {
		_c.SetWebhookURL(*v)
	}
	return _c
}

// SetEnabled sets the "enabled" field.
func (_c *VpnAlertRuleCreate) SetEnabled(v bool) *VpnAlertRuleCreate {
	_c.mutation.SetEnabled(v)
	return _c
}

// SetNillableEnabled sets the "enabled" field if the given value is not nil.
func (_c *VpnAlertRuleCreate) SetNillableEnabled(v *bool) *VpnAlertRuleCreate {
	if v != nil {
		_c.SetEnabled(*v)
	}
	return _c
}

// Mutation returns the VpnAlertRuleMutation object of the builder.
func (_c *VpnAlertRuleCreate) Mutation() *VpnAlertRuleMutation {
	return _c.mutation
}

// Save creates the VpnAlertRule in the database.
func (_c *VpnAlertRuleCreate) Save(ctx context.Context) (*VpnAlertRule, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VpnAlertRuleCreate) SaveX(ctx context.Context) *VpnAlertRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VpnAlertRuleCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VpnAlertRuleCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VpnAlertRuleCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := vpnalertrule.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := vpnalertrule.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
	if _, ok := _c.mutation.WebhookURL(); !ok {
		v := vpnalertrule.DefaultWebhookURL
		_c.mutation.SetWebhookURL(v)
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		v := vpnalertrule.DefaultEnabled
		_c.mutation.SetEnabled(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VpnAlertRuleCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VpnAlertRule.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "VpnAlertRule.updated_at"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "VpnAlertRule.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := vpnalertrule.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "VpnAlertRule.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Condition(); !ok {
		return &ValidationError{Name: "condition", err: errors.New(`ent: missing required field "VpnAlertRule.condition"`)}
	}
	if v, ok := _c.mutation.Condition(); ok {
		if err := vpnalertrule.ConditionValidator(v); err != nil {
			return &ValidationError{Name: "condition", err: fmt.Errorf(`ent: validator failed for field "VpnAlertRule.condition": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Threshold(); !ok {
		return &ValidationError{Name: "threshold", err: errors.New(`ent: missing required field "VpnAlertRule.threshold"`)}
	}
	if _, ok := _c.mutation.WebhookURL(); !ok {
		return &ValidationError{Name: "webhook_url", err: errors.New(`ent: missing required field "VpnAlertRule.webhook_url"`)}
	}
	if _, ok := _c.mutation.Enabled(); !ok {
		return &ValidationError{Name: "enabled", err: errors.New(`ent: missing required field "VpnAlertRule.enabled"`)}
	}
	return nil
}

func (_c *VpnAlertRuleCreate) sqlSave(ctx context.Context) (*VpnAlertRule, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VpnAlertRuleCreate) createSpec() (*VpnAlertRule, *sqlgraph.CreateSpec) {
	var (
		_node = &VpnAlertRule{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(vpnalertrule.Table, sqlgraph.NewFieldSpec(vpnalertrule.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(vpnalertrule.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(vpnalertrule.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(vpnalertrule.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.Condition(); ok {
		_spec.SetField(vpnalertrule.FieldCondition, field.TypeString, value)
		_node.Condition = value
	}
	if value, ok := _c.mutation.Threshold(); ok {
		_spec.SetField(vpnalertrule.FieldThreshold, field.TypeInt, value)
		_node.Threshold = value
	}
	if value, ok := _c.mutation.WebhookURL(); ok {
		_spec.SetField(vpnalertrule.FieldWebhookURL, field.TypeString, value)
		_node.WebhookURL = value
	}
	if value, ok := _c.mutation.Enabled(); ok {
		_spec.SetField(vpnalertrule.FieldEnabled, field.TypeBool, value)
		_node.Enabled = value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VpnAlertRule.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VpnAlertRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VpnAlertRuleCreate) OnConflict(opts ...sql.ConflictOption) *VpnAlertRuleUpsertOne {
	_c.conflict = opts
	return &VpnAlertRuleUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VpnAlertRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VpnAlertRuleCreate) OnConflictColumns(columns ...string) *VpnAlertRuleUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VpnAlertRuleUpsertOne{
		create: _c,
	}
}

type (
	// VpnAlertRuleUpsertOne is the builder for "upsert"-ing
	//  one VpnAlertRule node.
	VpnAlertRuleUpsertOne struct {
		create *VpnAlertRuleCreate
	}

	// VpnAlertRuleUpsert is the "OnConflict" setter.
	VpnAlertRuleUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *VpnAlertRuleUpsert) SetUpdatedAt(v time.Time) *VpnAlertRuleUpsert {
	u.Set(vpnalertrule.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VpnAlertRuleUpsert) UpdateUpdatedAt() *VpnAlertRuleUpsert {
	u.SetExcluded(vpnalertrule.FieldUpdatedAt)
	return u
}

// SetName sets the "name" field.
func (u *VpnAlertRuleUpsert) SetName(v string) *VpnAlertRuleUpsert {
	u.Set(vpnalertrule.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VpnAlertRuleUpsert) UpdateName() *VpnAlertRuleUpsert {
	u.SetExcluded(vpnalertrule.FieldName)
	return u
}

// SetCondition sets the "condition" field.
func (u *VpnAlertRuleUpsert) SetCondition(v string) *VpnAlertRuleUpsert {
	u.Set(vpnalertrule.FieldCondition, v)
	return u
}

// UpdateCondition sets the "condition" field to the value that was provided on create.
func (u *VpnAlertRuleUpsert) UpdateCondition() *VpnAlertRuleUpsert {
	u.SetExcluded(vpnalertrule.FieldCondition)
	return u
}

// SetThreshold sets the "threshold" field.
func (u *VpnAlertRuleUpsert) SetThreshold(v int) *VpnAlertRuleUpsert {
	u.Set(vpnalertrule.FieldThreshold, v)
	return u
}

// UpdateThreshold sets the "threshold" field to the value that was provided on create.
func (u *VpnAlertRuleUpsert) UpdateThreshold() *VpnAlertRuleUpsert {
	u.SetExcluded(vpnalertrule.FieldThreshold)
	return u
}

// AddThreshold adds v to the "threshold" field.
func (u *VpnAlertRuleUpsert) AddThreshold(v int) *VpnAlertRuleUpsert {
	u.Add(vpnalertrule.FieldThreshold, v)
	return u
}

// SetWebhookURL sets the "webhook_url" field.
func (u *VpnAlertRuleUpsert) SetWebhookURL(v string) *VpnAlertRuleUpsert {
	u.Set(vpnalertrule.FieldWebhookURL, v)
	return u
}

// UpdateWebhookURL sets the "webhook_url" field to the value that was provided on create.
func (u *VpnAlertRuleUpsert) UpdateWebhookURL() *VpnAlertRuleUpsert {
	u.SetExcluded(vpnalertrule.FieldWebhookURL)
	return u
}

// SetEnabled sets the "enabled" field.
func (u *VpnAlertRuleUpsert) SetEnabled(v bool) *VpnAlertRuleUpsert {
	u.Set(vpnalertrule.FieldEnabled, v)
	return u
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VpnAlertRuleUpsert) UpdateEnabled() *VpnAlertRuleUpsert {
	u.SetExcluded(vpnalertrule.FieldEnabled)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.VpnAlertRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VpnAlertRuleUpsertOne) UpdateNewValues() *VpnAlertRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(vpnalertrule.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VpnAlertRule.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *VpnAlertRuleUpsertOne) Ignore() *VpnAlertRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VpnAlertRuleUpsertOne) DoNothing() *VpnAlertRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VpnAlertRuleCreate.OnConflict
// documentation for more info.
func (u *VpnAlertRuleUpsertOne) Update(set func(*VpnAlertRuleUpsert)) *VpnAlertRuleUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VpnAlertRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VpnAlertRuleUpsertOne) SetUpdatedAt(v time.Time) *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertOne) UpdateUpdatedAt() *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *VpnAlertRuleUpsertOne) SetName(v string) *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertOne) UpdateName() *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateName()
	})
}

// SetCondition sets the "condition" field.
func (u *VpnAlertRuleUpsertOne) SetCondition(v string) *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetCondition(v)
	})
}

// UpdateCondition sets the "condition" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertOne) UpdateCondition() *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateCondition()
	})
}

// SetThreshold sets the "threshold" field.
func (u *VpnAlertRuleUpsertOne) SetThreshold(v int) *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetThreshold(v)
	})
}

// AddThreshold adds v to the "threshold" field.
func (u *VpnAlertRuleUpsertOne) AddThreshold(v int) *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.AddThreshold(v)
	})
}

// UpdateThreshold sets the "threshold" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertOne) UpdateThreshold() *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateThreshold()
	})
}

// SetWebhookURL sets the "webhook_url" field.
func (u *VpnAlertRuleUpsertOne) SetWebhookURL(v string) *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetWebhookURL(v)
	})
}

// UpdateWebhookURL sets the "webhook_url" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertOne) UpdateWebhookURL() *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateWebhookURL()
	})
}

// SetEnabled sets the "enabled" field.
func (u *VpnAlertRuleUpsertOne) SetEnabled(v bool) *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertOne) UpdateEnabled() *VpnAlertRuleUpsertOne {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *VpnAlertRuleUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VpnAlertRuleCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VpnAlertRuleUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *VpnAlertRuleUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *VpnAlertRuleUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// VpnAlertRuleCreateBulk is the builder for creating many VpnAlertRule entities in bulk.
type VpnAlertRuleCreateBulk struct {
	config
	err      error
	builders []*VpnAlertRuleCreate
	conflict []sql.ConflictOption
}

// Save creates the VpnAlertRule entities in the database.
func (_c *VpnAlertRuleCreateBulk) Save(ctx context.Context) ([]*VpnAlertRule, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VpnAlertRule, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VpnAlertRuleMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VpnAlertRuleCreateBulk) SaveX(ctx context.Context) []*VpnAlertRule {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VpnAlertRuleCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VpnAlertRuleCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.VpnAlertRule.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.VpnAlertRuleUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *VpnAlertRuleCreateBulk) OnConflict(opts ...sql.ConflictOption) *VpnAlertRuleUpsertBulk {
	_c.conflict = opts
	return &VpnAlertRuleUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.VpnAlertRule.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *VpnAlertRuleCreateBulk) OnConflictColumns(columns ...string) *VpnAlertRuleUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &VpnAlertRuleUpsertBulk{
		create: _c,
	}
}

// VpnAlertRuleUpsertBulk is the builder for "upsert"-ing
// a bulk of VpnAlertRule nodes.
type VpnAlertRuleUpsertBulk struct {
	create *VpnAlertRuleCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.VpnAlertRule.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *VpnAlertRuleUpsertBulk) UpdateNewValues() *VpnAlertRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(vpnalertrule.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.VpnAlertRule.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *VpnAlertRuleUpsertBulk) Ignore() *VpnAlertRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *VpnAlertRuleUpsertBulk) DoNothing() *VpnAlertRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the VpnAlertRuleCreateBulk.OnConflict
// documentation for more info.
func (u *VpnAlertRuleUpsertBulk) Update(set func(*VpnAlertRuleUpsert)) *VpnAlertRuleUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&VpnAlertRuleUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *VpnAlertRuleUpsertBulk) SetUpdatedAt(v time.Time) *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertBulk) UpdateUpdatedAt() *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetName sets the "name" field.
func (u *VpnAlertRuleUpsertBulk) SetName(v string) *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertBulk) UpdateName() *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateName()
	})
}

// SetCondition sets the "condition" field.
func (u *VpnAlertRuleUpsertBulk) SetCondition(v string) *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetCondition(v)
	})
}

// UpdateCondition sets the "condition" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertBulk) UpdateCondition() *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateCondition()
	})
}

// SetThreshold sets the "threshold" field.
func (u *VpnAlertRuleUpsertBulk) SetThreshold(v int) *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetThreshold(v)
	})
}

// AddThreshold adds v to the "threshold" field.
func (u *VpnAlertRuleUpsertBulk) AddThreshold(v int) *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.AddThreshold(v)
	})
}

// UpdateThreshold sets the "threshold" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertBulk) UpdateThreshold() *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateThreshold()
	})
}

// SetWebhookURL sets the "webhook_url" field.
func (u *VpnAlertRuleUpsertBulk) SetWebhookURL(v string) *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetWebhookURL(v)
	})
}

// UpdateWebhookURL sets the "webhook_url" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertBulk) UpdateWebhookURL() *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateWebhookURL()
	})
}

// SetEnabled sets the "enabled" field.
func (u *VpnAlertRuleUpsertBulk) SetEnabled(v bool) *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.SetEnabled(v)
	})
}

// UpdateEnabled sets the "enabled" field to the value that was provided on create.
func (u *VpnAlertRuleUpsertBulk) UpdateEnabled() *VpnAlertRuleUpsertBulk {
	return u.Update(func(s *VpnAlertRuleUpsert) {
		s.UpdateEnabled()
	})
}

// Exec executes the query.
func (u *VpnAlertRuleUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the VpnAlertRuleCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for VpnAlertRuleCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *VpnAlertRuleUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
