import Avatar from "./components/Avatar";
import Color from "./components/Color";
import Combine from "./components/Combine";
import Mono from "./components/Mono";
import Simple from "./components/Simple";
import Text from "./components/Text";
import { COLOR_GRADIENT, COLOR_PRIMARY, TITLE } from "./style";
var Icons = Mono;
Icons.Color = Color;
Icons.Text = Text;
Icons.Simple = Simple;
Icons.Combine = Combine;
Icons.Avatar = Avatar;
Icons.colorPrimary = COLOR_PRIMARY;
Icons.colorGradient = COLOR_GRADIENT;
Icons.title = TITLE;
export default Icons;