import Avatar from "./components/Avatar";
import BrandColor from "./components/BrandColor";
import BrandMono from "./components/BrandMono";
import Color from "./components/Color";
import Mono from "./components/Mono";
import { COLOR_PRIMARY, TITLE } from "./style";
var Icons = Mono;
Icons.Color = Color;
Icons.Brand = BrandMono;
Icons.BrandColor = BrandColor;
Icons.Avatar = Avatar;
Icons.colorPrimary = COLOR_PRIMARY;
Icons.title = TITLE;
export default Icons;