// Code generated by ent, DO NOT EDIT.

package vpnevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the vpnevent type in the database.
	Label = "vpn_event"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTunnelName holds the string denoting the tunnel_name field in the database.
	FieldTunnelName = "tunnel_name"
	// FieldEventType holds the string denoting the event_type field in the database.
	FieldEventType = "event_type"
	// FieldDetails holds the string denoting the details field in the database.
	FieldDetails = "details"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// Table holds the table name of the vpnevent in the database.
	Table = "vpn_events"
)

// Columns holds all SQL columns for vpnevent fields.
var Columns = []string{
	FieldID,
	FieldTunnelName,
	FieldEventType,
	FieldDetails,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// TunnelNameValidator is a validator for the "tunnel_name" field. It is called by the builders before save.
	TunnelNameValidator func(string) error
	// EventTypeValidator is a validator for the "event_type" field. It is called by the builders before save.
	EventTypeValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the VpnEvent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTunnelName orders the results by the tunnel_name field.
func ByTunnelName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTunnelName, opts...).ToFunc()
}

// ByEventType orders the results by the event_type field.
func ByEventType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEventType, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}
