// Code generated by ent, DO NOT EDIT.

package vpnevent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldLTE(FieldID, id))
}

// TunnelName applies equality check predicate on the "tunnel_name" field. It's identical to TunnelNameEQ.
func TunnelName(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldEQ(FieldTunnelName, v))
}

// EventType applies equality check predicate on the "event_type" field. It's identical to EventTypeEQ.
func EventType(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldEQ(FieldEventType, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// TunnelNameEQ applies the EQ predicate on the "tunnel_name" field.
func TunnelNameEQ(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldEQ(FieldTunnelName, v))
}

// TunnelNameNEQ applies the NEQ predicate on the "tunnel_name" field.
func TunnelNameNEQ(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldNEQ(FieldTunnelName, v))
}

// TunnelNameIn applies the In predicate on the "tunnel_name" field.
func TunnelNameIn(vs ...string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldIn(FieldTunnelName, vs...))
}

// TunnelNameNotIn applies the NotIn predicate on the "tunnel_name" field.
func TunnelNameNotIn(vs ...string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldNotIn(FieldTunnelName, vs...))
}

// TunnelNameGT applies the GT predicate on the "tunnel_name" field.
func TunnelNameGT(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldGT(FieldTunnelName, v))
}

// TunnelNameGTE applies the GTE predicate on the "tunnel_name" field.
func TunnelNameGTE(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldGTE(FieldTunnelName, v))
}

// TunnelNameLT applies the LT predicate on the "tunnel_name" field.
func TunnelNameLT(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldLT(FieldTunnelName, v))
}

// TunnelNameLTE applies the LTE predicate on the "tunnel_name" field.
func TunnelNameLTE(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldLTE(FieldTunnelName, v))
}

// TunnelNameContains applies the Contains predicate on the "tunnel_name" field.
func TunnelNameContains(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldContains(FieldTunnelName, v))
}

// TunnelNameHasPrefix applies the HasPrefix predicate on the "tunnel_name" field.
func TunnelNameHasPrefix(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldHasPrefix(FieldTunnelName, v))
}

// TunnelNameHasSuffix applies the HasSuffix predicate on the "tunnel_name" field.
func TunnelNameHasSuffix(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldHasSuffix(FieldTunnelName, v))
}

// TunnelNameEqualFold applies the EqualFold predicate on the "tunnel_name" field.
func TunnelNameEqualFold(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldEqualFold(FieldTunnelName, v))
}

// TunnelNameContainsFold applies the ContainsFold predicate on the "tunnel_name" field.
func TunnelNameContainsFold(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldContainsFold(FieldTunnelName, v))
}

// EventTypeEQ applies the EQ predicate on the "event_type" field.
func EventTypeEQ(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldEQ(FieldEventType, v))
}

// EventTypeNEQ applies the NEQ predicate on the "event_type" field.
func EventTypeNEQ(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldNEQ(FieldEventType, v))
}

// EventTypeIn applies the In predicate on the "event_type" field.
func EventTypeIn(vs ...string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldIn(FieldEventType, vs...))
}

// EventTypeNotIn applies the NotIn predicate on the "event_type" field.
func EventTypeNotIn(vs ...string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldNotIn(FieldEventType, vs...))
}

// EventTypeGT applies the GT predicate on the "event_type" field.
func EventTypeGT(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldGT(FieldEventType, v))
}

// EventTypeGTE applies the GTE predicate on the "event_type" field.
func EventTypeGTE(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldGTE(FieldEventType, v))
}

// EventTypeLT applies the LT predicate on the "event_type" field.
func EventTypeLT(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldLT(FieldEventType, v))
}

// EventTypeLTE applies the LTE predicate on the "event_type" field.
func EventTypeLTE(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldLTE(FieldEventType, v))
}

// EventTypeContains applies the Contains predicate on the "event_type" field.
func EventTypeContains(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldContains(FieldEventType, v))
}

// EventTypeHasPrefix applies the HasPrefix predicate on the "event_type" field.
func EventTypeHasPrefix(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldHasPrefix(FieldEventType, v))
}

// EventTypeHasSuffix applies the HasSuffix predicate on the "event_type" field.
func EventTypeHasSuffix(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldHasSuffix(FieldEventType, v))
}

// EventTypeEqualFold applies the EqualFold predicate on the "event_type" field.
func EventTypeEqualFold(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldEqualFold(FieldEventType, v))
}

// EventTypeContainsFold applies the ContainsFold predicate on the "event_type" field.
func EventTypeContainsFold(v string) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldContainsFold(FieldEventType, v))
}

// DetailsIsNil applies the IsNil predicate on the "details" field.
func DetailsIsNil() predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldIsNull(FieldDetails))
}

// DetailsNotNil applies the NotNil predicate on the "details" field.
func DetailsNotNil() predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldNotNull(FieldDetails))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.VpnEvent {
	return predicate.VpnEvent(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VpnEvent) predicate.VpnEvent {
	return predicate.VpnEvent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VpnEvent) predicate.VpnEvent {
	return predicate.VpnEvent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VpnEvent) predicate.VpnEvent {
	return predicate.VpnEvent(sql.NotPredicates(p))
}
