import { ColorScaleItem } from "./types.mjs";
import { blue } from "./colors/blue.mjs";
import { cyan } from "./colors/cyan.mjs";
import { geekblue } from "./colors/geekblue.mjs";
import { gold } from "./colors/gold.mjs";
import { gray } from "./colors/gray.mjs";
import { green } from "./colors/green.mjs";
import { lime } from "./colors/lime.mjs";
import { magenta } from "./colors/magenta.mjs";
import { orange } from "./colors/orange.mjs";
import { primary } from "./colors/primary.mjs";
import { purple } from "./colors/purple.mjs";
import { red } from "./colors/red.mjs";
import { volcano } from "./colors/volcano.mjs";
import { yellow } from "./colors/yellow.mjs";
import { colorScales } from "./colors/index.mjs";
import { ColorScales, ColorScalesProps } from "./ColorScales/index.mjs";
import { ColorScales as ColorScales$1 } from "./CssVar/index.mjs";
import { mauve } from "./neutrals/mauve.mjs";
import { olive } from "./neutrals/olive.mjs";
import { sage } from "./neutrals/sage.mjs";
import { sand } from "./neutrals/sand.mjs";
import { slate } from "./neutrals/slate.mjs";
import { NeutralColorScales, neutralColorScales } from "./neutrals/index.mjs";
export { type ColorScaleItem, ColorScales, type ColorScalesProps, ColorScales$1 as CssVar, NeutralColorScales, blue, colorScales, colorScales as colors, cyan, geekblue, gold, gray, green, lime, magenta, mauve, neutralColorScales, neutralColorScales as neutrals, olive, orange, primary, purple, red, sage, sand, slate, volcano, yellow };