// Code generated by ent, DO NOT EDIT.

package referralcommission

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldID, id))
}

// InviterID applies equality check predicate on the "inviter_id" field. It's identical to InviterIDEQ.
func InviterID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldInviterID, v))
}

// InviteeID applies equality check predicate on the "invitee_id" field. It's identical to InviteeIDEQ.
func InviteeID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldInviteeID, v))
}

// OrderID applies equality check predicate on the "order_id" field. It's identical to OrderIDEQ.
func OrderID(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldOrderID, v))
}

// OrderAmountUsd applies equality check predicate on the "order_amount_usd" field. It's identical to OrderAmountUsdEQ.
func OrderAmountUsd(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldOrderAmountUsd, v))
}

// CommissionRate applies equality check predicate on the "commission_rate" field. It's identical to CommissionRateEQ.
func CommissionRate(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCommissionRate, v))
}

// CommissionAmount applies equality check predicate on the "commission_amount" field. It's identical to CommissionAmountEQ.
func CommissionAmount(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCommissionAmount, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldStatus, v))
}

// SettledAt applies equality check predicate on the "settled_at" field. It's identical to SettledAtEQ.
func SettledAt(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSettledAt, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// InviterIDEQ applies the EQ predicate on the "inviter_id" field.
func InviterIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldInviterID, v))
}

// InviterIDNEQ applies the NEQ predicate on the "inviter_id" field.
func InviterIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldInviterID, v))
}

// InviterIDIn applies the In predicate on the "inviter_id" field.
func InviterIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldInviterID, vs...))
}

// InviterIDNotIn applies the NotIn predicate on the "inviter_id" field.
func InviterIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldInviterID, vs...))
}

// InviterIDGT applies the GT predicate on the "inviter_id" field.
func InviterIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldInviterID, v))
}

// InviterIDGTE applies the GTE predicate on the "inviter_id" field.
func InviterIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldInviterID, v))
}

// InviterIDLT applies the LT predicate on the "inviter_id" field.
func InviterIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldInviterID, v))
}

// InviterIDLTE applies the LTE predicate on the "inviter_id" field.
func InviterIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldInviterID, v))
}

// InviteeIDEQ applies the EQ predicate on the "invitee_id" field.
func InviteeIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldInviteeID, v))
}

// InviteeIDNEQ applies the NEQ predicate on the "invitee_id" field.
func InviteeIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldInviteeID, v))
}

// InviteeIDIn applies the In predicate on the "invitee_id" field.
func InviteeIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldInviteeID, vs...))
}

// InviteeIDNotIn applies the NotIn predicate on the "invitee_id" field.
func InviteeIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldInviteeID, vs...))
}

// InviteeIDGT applies the GT predicate on the "invitee_id" field.
func InviteeIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldInviteeID, v))
}

// InviteeIDGTE applies the GTE predicate on the "invitee_id" field.
func InviteeIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldInviteeID, v))
}

// InviteeIDLT applies the LT predicate on the "invitee_id" field.
func InviteeIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldInviteeID, v))
}

// InviteeIDLTE applies the LTE predicate on the "invitee_id" field.
func InviteeIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldInviteeID, v))
}

// OrderIDEQ applies the EQ predicate on the "order_id" field.
func OrderIDEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldOrderID, v))
}

// OrderIDNEQ applies the NEQ predicate on the "order_id" field.
func OrderIDNEQ(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldOrderID, v))
}

// OrderIDIn applies the In predicate on the "order_id" field.
func OrderIDIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldOrderID, vs...))
}

// OrderIDNotIn applies the NotIn predicate on the "order_id" field.
func OrderIDNotIn(vs ...int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldOrderID, vs...))
}

// OrderIDGT applies the GT predicate on the "order_id" field.
func OrderIDGT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldOrderID, v))
}

// OrderIDGTE applies the GTE predicate on the "order_id" field.
func OrderIDGTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldOrderID, v))
}

// OrderIDLT applies the LT predicate on the "order_id" field.
func OrderIDLT(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldOrderID, v))
}

// OrderIDLTE applies the LTE predicate on the "order_id" field.
func OrderIDLTE(v int64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldOrderID, v))
}

// OrderAmountUsdEQ applies the EQ predicate on the "order_amount_usd" field.
func OrderAmountUsdEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldOrderAmountUsd, v))
}

// OrderAmountUsdNEQ applies the NEQ predicate on the "order_amount_usd" field.
func OrderAmountUsdNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldOrderAmountUsd, v))
}

// OrderAmountUsdIn applies the In predicate on the "order_amount_usd" field.
func OrderAmountUsdIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldOrderAmountUsd, vs...))
}

// OrderAmountUsdNotIn applies the NotIn predicate on the "order_amount_usd" field.
func OrderAmountUsdNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldOrderAmountUsd, vs...))
}

// OrderAmountUsdGT applies the GT predicate on the "order_amount_usd" field.
func OrderAmountUsdGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldOrderAmountUsd, v))
}

// OrderAmountUsdGTE applies the GTE predicate on the "order_amount_usd" field.
func OrderAmountUsdGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldOrderAmountUsd, v))
}

// OrderAmountUsdLT applies the LT predicate on the "order_amount_usd" field.
func OrderAmountUsdLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldOrderAmountUsd, v))
}

// OrderAmountUsdLTE applies the LTE predicate on the "order_amount_usd" field.
func OrderAmountUsdLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldOrderAmountUsd, v))
}

// CommissionRateEQ applies the EQ predicate on the "commission_rate" field.
func CommissionRateEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCommissionRate, v))
}

// CommissionRateNEQ applies the NEQ predicate on the "commission_rate" field.
func CommissionRateNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldCommissionRate, v))
}

// CommissionRateIn applies the In predicate on the "commission_rate" field.
func CommissionRateIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldCommissionRate, vs...))
}

// CommissionRateNotIn applies the NotIn predicate on the "commission_rate" field.
func CommissionRateNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldCommissionRate, vs...))
}

// CommissionRateGT applies the GT predicate on the "commission_rate" field.
func CommissionRateGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldCommissionRate, v))
}

// CommissionRateGTE applies the GTE predicate on the "commission_rate" field.
func CommissionRateGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldCommissionRate, v))
}

// CommissionRateLT applies the LT predicate on the "commission_rate" field.
func CommissionRateLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldCommissionRate, v))
}

// CommissionRateLTE applies the LTE predicate on the "commission_rate" field.
func CommissionRateLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldCommissionRate, v))
}

// CommissionAmountEQ applies the EQ predicate on the "commission_amount" field.
func CommissionAmountEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCommissionAmount, v))
}

// CommissionAmountNEQ applies the NEQ predicate on the "commission_amount" field.
func CommissionAmountNEQ(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldCommissionAmount, v))
}

// CommissionAmountIn applies the In predicate on the "commission_amount" field.
func CommissionAmountIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldCommissionAmount, vs...))
}

// CommissionAmountNotIn applies the NotIn predicate on the "commission_amount" field.
func CommissionAmountNotIn(vs ...float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldCommissionAmount, vs...))
}

// CommissionAmountGT applies the GT predicate on the "commission_amount" field.
func CommissionAmountGT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldCommissionAmount, v))
}

// CommissionAmountGTE applies the GTE predicate on the "commission_amount" field.
func CommissionAmountGTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldCommissionAmount, v))
}

// CommissionAmountLT applies the LT predicate on the "commission_amount" field.
func CommissionAmountLT(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldCommissionAmount, v))
}

// CommissionAmountLTE applies the LTE predicate on the "commission_amount" field.
func CommissionAmountLTE(v float64) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldCommissionAmount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldContainsFold(FieldStatus, v))
}

// SettledAtEQ applies the EQ predicate on the "settled_at" field.
func SettledAtEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldSettledAt, v))
}

// SettledAtNEQ applies the NEQ predicate on the "settled_at" field.
func SettledAtNEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldSettledAt, v))
}

// SettledAtIn applies the In predicate on the "settled_at" field.
func SettledAtIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldSettledAt, vs...))
}

// SettledAtNotIn applies the NotIn predicate on the "settled_at" field.
func SettledAtNotIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldSettledAt, vs...))
}

// SettledAtGT applies the GT predicate on the "settled_at" field.
func SettledAtGT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldSettledAt, v))
}

// SettledAtGTE applies the GTE predicate on the "settled_at" field.
func SettledAtGTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldSettledAt, v))
}

// SettledAtLT applies the LT predicate on the "settled_at" field.
func SettledAtLT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldSettledAt, v))
}

// SettledAtLTE applies the LTE predicate on the "settled_at" field.
func SettledAtLTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldSettledAt, v))
}

// SettledAtIsNil applies the IsNil predicate on the "settled_at" field.
func SettledAtIsNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIsNull(FieldSettledAt))
}

// SettledAtNotNil applies the NotNil predicate on the "settled_at" field.
func SettledAtNotNil() predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotNull(FieldSettledAt))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.FieldLTE(FieldCreatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ReferralCommission) predicate.ReferralCommission {
	return predicate.ReferralCommission(sql.NotPredicates(p))
}
