// Code generated by ent, DO NOT EDIT.

package proxy

import (
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the proxy type in the database.
	Label = "proxy"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldDeletedAt holds the string denoting the deleted_at field in the database.
	FieldDeletedAt = "deleted_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldProtocol holds the string denoting the protocol field in the database.
	FieldProtocol = "protocol"
	// FieldHost holds the string denoting the host field in the database.
	FieldHost = "host"
	// FieldPort holds the string denoting the port field in the database.
	FieldPort = "port"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldPassword holds the string denoting the password field in the database.
	FieldPassword = "password"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldRegion holds the string denoting the region field in the database.
	FieldRegion = "region"
	// FieldGroupName holds the string denoting the group_name field in the database.
	FieldGroupName = "group_name"
	// FieldOvpnConfig holds the string denoting the ovpn_config field in the database.
	FieldOvpnConfig = "ovpn_config"
	// FieldOvpnUsername holds the string denoting the ovpn_username field in the database.
	FieldOvpnUsername = "ovpn_username"
	// FieldOvpnPassword holds the string denoting the ovpn_password field in the database.
	FieldOvpnPassword = "ovpn_password"
	// FieldIsDedicated holds the string denoting the is_dedicated field in the database.
	FieldIsDedicated = "is_dedicated"
	// FieldVpnStatus holds the string denoting the vpn_status field in the database.
	FieldVpnStatus = "vpn_status"
	// FieldVpnExitIP holds the string denoting the vpn_exit_ip field in the database.
	FieldVpnExitIP = "vpn_exit_ip"
	// FieldHealthStatus holds the string denoting the health_status field in the database.
	FieldHealthStatus = "health_status"
	// FieldLatencyMs holds the string denoting the latency_ms field in the database.
	FieldLatencyMs = "latency_ms"
	// FieldLastHealthAt holds the string denoting the last_health_at field in the database.
	FieldLastHealthAt = "last_health_at"
	// FieldHealthCheckFailures holds the string denoting the health_check_failures field in the database.
	FieldHealthCheckFailures = "health_check_failures"
	// FieldProxyType holds the string denoting the proxy_type field in the database.
	FieldProxyType = "proxy_type"
	// FieldPriority holds the string denoting the priority field in the database.
	FieldPriority = "priority"
	// FieldConfigVersion holds the string denoting the config_version field in the database.
	FieldConfigVersion = "config_version"
	// FieldLastConnectedAt holds the string denoting the last_connected_at field in the database.
	FieldLastConnectedAt = "last_connected_at"
	// FieldConfigStale holds the string denoting the config_stale field in the database.
	FieldConfigStale = "config_stale"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// Table holds the table name of the proxy in the database.
	Table = "proxies"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "proxy_id"
)

// Columns holds all SQL columns for proxy fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldDeletedAt,
	FieldName,
	FieldProtocol,
	FieldHost,
	FieldPort,
	FieldUsername,
	FieldPassword,
	FieldStatus,
	FieldRegion,
	FieldGroupName,
	FieldOvpnConfig,
	FieldOvpnUsername,
	FieldOvpnPassword,
	FieldIsDedicated,
	FieldVpnStatus,
	FieldVpnExitIP,
	FieldHealthStatus,
	FieldLatencyMs,
	FieldLastHealthAt,
	FieldHealthCheckFailures,
	FieldProxyType,
	FieldPriority,
	FieldConfigVersion,
	FieldLastConnectedAt,
	FieldConfigStale,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// Note that the variables below are initialized by the runtime
// package on the initialization of the application. Therefore,
// it should be imported in the main as follows:
//
//	import _ "github.com/Wei-Shaw/sub2api/ent/runtime"
var (
	Hooks        [1]ent.Hook
	Interceptors [1]ent.Interceptor
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// ProtocolValidator is a validator for the "protocol" field. It is called by the builders before save.
	ProtocolValidator func(string) error
	// HostValidator is a validator for the "host" field. It is called by the builders before save.
	HostValidator func(string) error
	// UsernameValidator is a validator for the "username" field. It is called by the builders before save.
	UsernameValidator func(string) error
	// PasswordValidator is a validator for the "password" field. It is called by the builders before save.
	PasswordValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// RegionValidator is a validator for the "region" field. It is called by the builders before save.
	RegionValidator func(string) error
	// GroupNameValidator is a validator for the "group_name" field. It is called by the builders before save.
	GroupNameValidator func(string) error
	// OvpnUsernameValidator is a validator for the "ovpn_username" field. It is called by the builders before save.
	OvpnUsernameValidator func(string) error
	// OvpnPasswordValidator is a validator for the "ovpn_password" field. It is called by the builders before save.
	OvpnPasswordValidator func(string) error
	// DefaultIsDedicated holds the default value on creation for the "is_dedicated" field.
	DefaultIsDedicated bool
	// VpnStatusValidator is a validator for the "vpn_status" field. It is called by the builders before save.
	VpnStatusValidator func(string) error
	// VpnExitIPValidator is a validator for the "vpn_exit_ip" field. It is called by the builders before save.
	VpnExitIPValidator func(string) error
	// HealthStatusValidator is a validator for the "health_status" field. It is called by the builders before save.
	HealthStatusValidator func(string) error
	// DefaultHealthCheckFailures holds the default value on creation for the "health_check_failures" field.
	DefaultHealthCheckFailures int
	// DefaultProxyType holds the default value on creation for the "proxy_type" field.
	DefaultProxyType string
	// ProxyTypeValidator is a validator for the "proxy_type" field. It is called by the builders before save.
	ProxyTypeValidator func(string) error
	// DefaultPriority holds the default value on creation for the "priority" field.
	DefaultPriority int
	// DefaultConfigVersion holds the default value on creation for the "config_version" field.
	DefaultConfigVersion int
	// DefaultConfigStale holds the default value on creation for the "config_stale" field.
	DefaultConfigStale bool
)

// OrderOption defines the ordering options for the Proxy queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByDeletedAt orders the results by the deleted_at field.
func ByDeletedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDeletedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByProtocol orders the results by the protocol field.
func ByProtocol(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProtocol, opts...).ToFunc()
}

// ByHost orders the results by the host field.
func ByHost(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHost, opts...).ToFunc()
}

// ByPort orders the results by the port field.
func ByPort(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPort, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByPassword orders the results by the password field.
func ByPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPassword, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByRegion orders the results by the region field.
func ByRegion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRegion, opts...).ToFunc()
}

// ByGroupName orders the results by the group_name field.
func ByGroupName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGroupName, opts...).ToFunc()
}

// ByOvpnConfig orders the results by the ovpn_config field.
func ByOvpnConfig(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOvpnConfig, opts...).ToFunc()
}

// ByOvpnUsername orders the results by the ovpn_username field.
func ByOvpnUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOvpnUsername, opts...).ToFunc()
}

// ByOvpnPassword orders the results by the ovpn_password field.
func ByOvpnPassword(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOvpnPassword, opts...).ToFunc()
}

// ByIsDedicated orders the results by the is_dedicated field.
func ByIsDedicated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsDedicated, opts...).ToFunc()
}

// ByVpnStatus orders the results by the vpn_status field.
func ByVpnStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVpnStatus, opts...).ToFunc()
}

// ByVpnExitIP orders the results by the vpn_exit_ip field.
func ByVpnExitIP(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVpnExitIP, opts...).ToFunc()
}

// ByHealthStatus orders the results by the health_status field.
func ByHealthStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHealthStatus, opts...).ToFunc()
}

// ByLatencyMs orders the results by the latency_ms field.
func ByLatencyMs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLatencyMs, opts...).ToFunc()
}

// ByLastHealthAt orders the results by the last_health_at field.
func ByLastHealthAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastHealthAt, opts...).ToFunc()
}

// ByHealthCheckFailures orders the results by the health_check_failures field.
func ByHealthCheckFailures(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldHealthCheckFailures, opts...).ToFunc()
}

// ByProxyType orders the results by the proxy_type field.
func ByProxyType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyType, opts...).ToFunc()
}

// ByPriority orders the results by the priority field.
func ByPriority(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPriority, opts...).ToFunc()
}

// ByConfigVersion orders the results by the config_version field.
func ByConfigVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigVersion, opts...).ToFunc()
}

// ByLastConnectedAt orders the results by the last_connected_at field.
func ByLastConnectedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastConnectedAt, opts...).ToFunc()
}

// ByConfigStale orders the results by the config_stale field.
func ByConfigStale(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldConfigStale, opts...).ToFunc()
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, AccountsTable, AccountsColumn),
	)
}
